<?php
defined('_JEXEC') or die;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Session\Session;
use Joomla\CMS\Uri\Uri;
$d=$this->data;$items=$d['items'];$state=$d['state'];$root=rtrim(Uri::root(true),'/');$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$num=static fn($v,$suffix='')=>(trim((string)$v)!==''&&(float)$v!==0.0?htmlspecialchars((string)$v).$suffix:'–');
$availability=static fn($v)=>match((string)$v){'available'=>'Verfügbar','low_stock'=>'Wenige verfügbar','sold_out'=>'Ausverkauft','preorder'=>'Vorbestellbar',default=>(string)$v?:'–'};
$rows=['Hersteller'=>fn($p)=>$p->manufacturer_name?:'–','Preis'=>fn($p)=>number_format((int)$p->discount_active&&$p->discount_price>0?(float)$p->discount_price:(float)$p->sale_price,2,',','.').' '.$p->currency,'Verfügbarkeit'=>fn($p)=>$availability($p->in_stock),'NEM'=>fn($p)=>$num($p->nem,' g'),'Schusszahl'=>fn($p)=>$num($p->shot_count),'Kaliber'=>fn($p)=>$num($p->caliber),'Brenndauer'=>fn($p)=>$num($p->burn_time),'Steighöhe'=>fn($p)=>$num($p->rise_height)];
?>
<main class="fdshop-comparison-page" data-comparison-page data-token="<?php echo Session::getFormToken();?>"><header><h1>Produktvergleich</h1><p><?php echo count($items);?> von <?php echo(int)$state['max'];?> Produkten ausgewählt</p></header><?php if(!$items):?><div class="fdshop-comparison-empty"><h2>Noch keine Produkte ausgewählt</h2><p>Nutze „Vergleichen“ an Produkten derselben Kategorie.</p></div><?php else:?><div class="fdshop-comparison-tools"><label><input type="checkbox" data-comparison-differences> Nur Unterschiede anzeigen</label><button class="btn btn-outline-secondary" type="button" data-comparison-clear>Vergleich leeren</button></div><div class="fdshop-comparison-scroll"><div class="fdshop-comparison-grid" style="--compare-count:<?php echo count($items);?>"><div class="fdshop-comparison-label fdshop-comparison-label--head">Produkt</div><?php foreach($items as$p):?><article class="fdshop-comparison-product" data-product-id="<?php echo(int)$p->id;?>"><?php $img=$p->image?$root.'/'.ltrim($p->image,'/'):$root.'/media/com_fdshop/images/product-placeholder.svg';?><img src="<?php echo$e($img);?>" alt="<?php echo$e($p->product_name);?>"><strong><?php echo$e($p->product_name);?></strong><button type="button" class="btn btn-sm btn-outline-danger" data-comparison-remove="<?php echo(int)$p->id;?>">Entfernen</button></article><?php endforeach;?><?php foreach($rows as$label=>$value):$values=array_map($value,$items);$normal=array_map(fn($v)=>mb_strtolower(trim(strip_tags((string)$v))),$values);?><div class="fdshop-comparison-row-label" data-compare-row="<?php echo$e($label);?>"><?php echo$e($label);?></div><?php foreach($values as$v):?><div class="fdshop-comparison-value" data-compare-value="<?php echo$e($v);?>"><?php echo$e($v);?></div><?php endforeach;?><?php endforeach;?></div></div><?php endif;?><section class="fdshop-comparison-saved"><h2>Gespeicherte Vergleiche</h2><?php if(!$d['user_id']):?><p>Zum dauerhaften Speichern bitte <a href="<?php echo Route::_('index.php?option=com_users&view=login');?>">anmelden</a> oder <a href="<?php echo Route::_('index.php?option=com_users&view=registration');?>">registrieren</a>. Dein aktiver Vergleich bleibt in dieser Sitzung erhalten.</p><?php else:?><form data-comparison-save><label>Name <input name="name" maxlength="100" required></label><button class="btn btn-secondary">Aktuellen Vergleich speichern</button></form><div data-comparison-saved><?php foreach($d['saved']as$list):?><article data-comparison-list="<?php echo(int)$list->id;?>"><strong><?php echo$e($list->name);?></strong> <small><?php echo(int)$list->product_count;?> Produkte</small><button type="button" data-comparison-activate>Öffnen</button><button type="button" data-comparison-rename>Umbenennen</button><button type="button" data-comparison-delete>Löschen</button></article><?php endforeach;?></div><?php endif;?></section></main>
