<?php
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper; use Joomla\CMS\Router\Route;
$ranges=$this->item->ranges??[];
?>
<form action="<?php echo Route::_('index.php?option=com_fdshop&view=filter&layout=edit&id='.(int)($this->item->id??0));?>" method="post" name="adminForm" id="adminForm">
<div class="card mb-3"><div class="card-header">Systemfilter</div><div class="card-body"><?php echo $this->form->renderFieldset('basic');?></div></div>
<?php if(in_array((string)($this->item->filter_key??''),['duration','caliber','nem'],true)): ?>
<div class="card"><div class="card-header">Bereiche</div><div class="card-body"><p class="text-muted">Grenzen gelten als [Von, Bis): Von ist inklusive, Bis exklusiv. Eine Grenze darf für offene Bereiche leer bleiben.</p><div class="table-responsive"><table class="table" id="fdshop-filter-ranges"><thead><tr><th>Bezeichnung</th><th>Von</th><th>Bis</th><th>Aktiv</th><th>Reihenfolge</th><th>Entfernen</th></tr></thead><tbody>
<?php foreach($ranges as $i=>$range): ?><tr><td><input class="form-control" required name="jform[ranges][<?php echo $i;?>][label]" value="<?php echo $this->escape($range->label);?>"><input type="hidden" name="jform[ranges][<?php echo $i;?>][id]" value="<?php echo (int)$range->id;?>"></td><td><input class="form-control" type="number" step="0.001" name="jform[ranges][<?php echo $i;?>][value_from]" value="<?php echo $range->value_from===null?'':$this->escape($range->value_from);?>"></td><td><input class="form-control" type="number" step="0.001" name="jform[ranges][<?php echo $i;?>][value_to]" value="<?php echo $range->value_to===null?'':$this->escape($range->value_to);?>"></td><td><input type="checkbox" name="jform[ranges][<?php echo $i;?>][is_active]" value="1"<?php echo (int)$range->is_active===1?' checked':'';?>></td><td><input class="form-control" type="number" name="jform[ranges][<?php echo $i;?>][ordering]" value="<?php echo (int)$range->ordering;?>"></td><td><input type="checkbox" name="jform[ranges][<?php echo $i;?>][delete]" value="1" aria-label="Bereich entfernen"></td></tr><?php endforeach;?>
</tbody></table></div><button class="btn btn-secondary" type="button" data-add-range>Bereich hinzufügen</button></div></div>
<script>document.querySelector('[data-add-range]').addEventListener('click',function(){var b=document.querySelector('#fdshop-filter-ranges tbody'),i=b.rows.length,r=b.insertRow();r.innerHTML='<td><input class="form-control" required name="jform[ranges]['+i+'][label]"></td><td><input class="form-control" type="number" step="0.001" name="jform[ranges]['+i+'][value_from]"></td><td><input class="form-control" type="number" step="0.001" name="jform[ranges]['+i+'][value_to]"></td><td><input type="checkbox" name="jform[ranges]['+i+'][is_active]" value="1" checked></td><td><input class="form-control" type="number" name="jform[ranges]['+i+'][ordering]" value="'+((i+1)*10)+'"></td><td><button class="btn btn-danger btn-sm" type="button" onclick="this.closest(\'tr\').remove()">Entfernen</button></td>';});</script>
<?php endif; ?>
<input type="hidden" name="task" value=""><?php echo HTMLHelper::_('form.token');?></form>
