<?php
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper; use Joomla\CMS\Router\Route;
$ranges=$this->item->ranges??[];$options=$this->item->options??[];$categories=$this->item->categories??[];
$categorySelect=static function(string $name,array $selected)use($categories){$html='<select class="form-select" multiple size="5" name="'.$name.'[]">';foreach($categories as$c){$html.='<option value="'.(int)$c->id.'"'.(in_array((int)$c->id,$selected,true)?' selected':'').'>'.htmlspecialchars((string)$c->category_name,ENT_QUOTES,'UTF-8').'</option>'; }return $html.'</select><small class="form-text">Leer = global</small>';};
?>
<form action="<?php echo Route::_('index.php?option=com_fdshop&view=filter&layout=edit&id='.(int)($this->item->id??0));?>" method="post" name="adminForm" id="adminForm">
<div class="card mb-3"><div class="card-header">Systemfilter</div><div class="card-body"><?php echo $this->form->renderFieldset('basic');?></div></div>
<?php if(in_array((string)($this->item->filter_key??''),['duration','caliber','nem'],true)): ?>
<div class="card"><div class="card-header">Bereiche</div><div class="card-body"><p class="text-muted">Grenzen gelten als [Von, Bis): Von ist inklusive, Bis exklusiv. Eine Grenze darf für offene Bereiche leer bleiben.</p><div class="table-responsive"><table class="table" id="fdshop-filter-ranges"><thead><tr><th>Bezeichnung</th><th>Von</th><th>Bis</th><th>Aktiv</th><th>Reihenfolge</th><th>Kategorien</th><th>Entfernen</th></tr></thead><tbody>
<?php foreach($ranges as $i=>$range): ?><tr><td><input class="form-control" required name="jform[ranges][<?php echo $i;?>][label]" value="<?php echo $this->escape($range->label);?>"><input type="hidden" name="jform[ranges][<?php echo $i;?>][id]" value="<?php echo (int)$range->id;?>"></td><td><input class="form-control" type="number" step="0.001" name="jform[ranges][<?php echo $i;?>][value_from]" value="<?php echo $range->value_from===null?'':$this->escape($range->value_from);?>"></td><td><input class="form-control" type="number" step="0.001" name="jform[ranges][<?php echo $i;?>][value_to]" value="<?php echo $range->value_to===null?'':$this->escape($range->value_to);?>"></td><td><input type="checkbox" name="jform[ranges][<?php echo $i;?>][is_active]" value="1"<?php echo (int)$range->is_active===1?' checked':'';?>></td><td><input class="form-control" type="number" name="jform[ranges][<?php echo $i;?>][ordering]" value="<?php echo (int)$range->ordering;?>"></td><td><?php echo $categorySelect('jform[ranges]['.$i.'][category_ids]',array_map('intval',$range->category_ids??[]));?></td><td><input type="checkbox" name="jform[ranges][<?php echo $i;?>][delete]" value="1" aria-label="Bereich entfernen"></td></tr><?php endforeach;?>
</tbody></table></div><button class="btn btn-secondary" type="button" data-add-range>Bereich hinzufügen</button></div></div>
<script>document.querySelector('[data-add-range]').addEventListener('click',function(){var b=document.querySelector('#fdshop-filter-ranges tbody'),i=b.rows.length,r=b.insertRow();r.innerHTML='<td><input class="form-control" required name="jform[ranges]['+i+'][label]"></td><td><input class="form-control" type="number" step="0.001" name="jform[ranges]['+i+'][value_from]"></td><td><input class="form-control" type="number" step="0.001" name="jform[ranges]['+i+'][value_to]"></td><td><input type="checkbox" name="jform[ranges]['+i+'][is_active]" value="1" checked></td><td><input class="form-control" type="number" name="jform[ranges]['+i+'][ordering]" value="'+((i+1)*10)+'"></td><td><small>Nach dem ersten Speichern zuweisbar</small></td><td><button class="btn btn-danger btn-sm" type="button" onclick="this.closest(\'tr\').remove()">Entfernen</button></td>';});</script>
<?php endif; ?>
<?php if(in_array((string)($this->item->filter_key??''),['firing_type','product_type'],true)): ?>
<div class="card mt-3"><div class="card-header">Optionen</div><div class="card-body"><p class="text-muted">Technische Schlüssel sind stabil und nicht editierbar. Optionen werden deaktiviert statt gelöscht.</p><table class="table"><thead><tr><th>Schlüssel</th><th>Bezeichnung</th><th>Aktiv</th><th>Reihenfolge</th><th>Kategorien</th></tr></thead><tbody>
<?php foreach($options as$i=>$option):?><tr><td><code><?php echo $this->escape($option->option_key);?></code><input type="hidden" name="jform[options][<?php echo$i;?>][id]" value="<?php echo(int)$option->id;?>"></td><td><input class="form-control" required name="jform[options][<?php echo$i;?>][label]" value="<?php echo$this->escape($option->label);?>"></td><td><input type="checkbox" name="jform[options][<?php echo$i;?>][is_active]" value="1"<?php echo(int)$option->is_active===1?' checked':'';?>></td><td><input class="form-control" type="number" name="jform[options][<?php echo$i;?>][ordering]" value="<?php echo(int)$option->ordering;?>"></td><td><?php echo$categorySelect('jform[options]['.$i.'][category_ids]',array_map('intval',$option->category_ids??[]));?></td></tr><?php endforeach;?>
</tbody></table></div></div>
<?php endif;?>
<input type="hidden" name="task" value=""><?php echo HTMLHelper::_('form.token');?></form>
