const { test, expect } = require('@playwright/test');
const { installDiagnostics } = require('../support/browser');

test('Joomla registration and profile persist FDShop customer data without a third visible name field', async ({ page, baseURL }) => {
  const diagnostics = await installDiagnostics(page, baseURL);
  const response = await page.goto('/index.php?option=com_users&view=registration');
  expect(response?.status()).toBe(200);
  const form = page.locator('#member-registration');
  const entry = page.locator('.fdshop-account-entry');
  await expect(entry.getByRole('heading', { name: /already registered|bereits registriert/i })).toBeVisible();
  await expect(entry.getByRole('heading', { name: /registration|registrierung/i })).toBeVisible();
  const desktopBoxes = await entry.locator(':scope > section').evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect()));
  expect(desktopBoxes[0].left).toBeLessThan(desktopBoxes[1].left);
  await expect(entry.getByRole('link', { name: /password|passwort/i })).toHaveAttribute('href', /(view=reset|users\/reset)/);
  await expect(entry.getByRole('link', { name: /username|benutzername/i })).toHaveAttribute('href', /(view=remind|users\/remind)/);
  const fieldOrder = await form.locator('input[id^="jform_"]').evaluateAll(nodes => nodes.map(node => node.id));
  expect(fieldOrder.indexOf('jform_email1')).toBeLessThan(fieldOrder.indexOf('jform_username'));
  expect(fieldOrder.indexOf('jform_fdshop_customer_first_name')).toBeLessThan(fieldOrder.indexOf('jform_fdshop_customer_last_name'));
  await page.setViewportSize({ width: 480, height: 900 });
  const mobileBoxes = await entry.locator(':scope > section').evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect()));
  expect(mobileBoxes[0].top).toBeLessThan(mobileBoxes[1].top);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true);
  await page.setViewportSize({ width: 1280, height: 900 });
  await expect(form.locator('input[name="jform[name]"]')).toBeHidden();
  await form.getByLabel(/First name|Vorname/i).fill('Max');
  await form.getByLabel(/Last name|Nachname/i).fill('Beispiel');
  await expect(form.getByLabel(/Company|Firma/i)).not.toHaveAttribute('required', '');
  await form.getByLabel(/Street and house number|Straße \+ Hausnummer/i).fill('Musterweg 7');
  await form.getByLabel(/Postal code|PLZ/i).fill('54321');
  await form.getByLabel(/City|Ort/i).fill('Beispielstadt');
  await expect(form.getByLabel(/Country|Land/i)).toHaveValue('Deutschland');
  await form.getByLabel(/Phone|Telefon/i).fill('+49 40 123456');
  await form.locator('#jform_username').fill('fdshop_customer_e2e');
  await form.locator('#jform_password1').fill('FDShop-Test-2026!');
  await form.locator('#jform_password2').fill('FDShop-Test-2026!');
  await form.locator('#jform_email1').fill('fdshop-customer-e2e@example.test');
  await form.getByRole('button', { name: /Registrieren|Register/i }).click();
  await expect(page.locator('input[name="jform[username]"]')).toHaveCount(0);
  await expect(page.locator('#system-message-container')).not.toBeEmpty();

  await page.goto('/index.php?option=com_users&view=registration');
  const login = page.locator('.fdshop-account-entry__login form');
  await login.locator('input[name="username"]').fill('fdshop_customer_e2e');
  await login.locator('input[name="password"]').fill('FDShop-Test-2026!');
  await login.getByRole('button', { name: /Log in|Anmelden/i }).click();
  await expect(login).toHaveCount(0);

  await page.goto('/index.php?option=com_users&view=profile&layout=edit');
  await expect(page.getByLabel(/First name|Vorname/i)).toHaveValue('Max');
  await expect(page.getByLabel(/Last name|Nachname/i)).toHaveValue('Beispiel');
  await expect(page.getByLabel(/City|Ort/i)).toHaveValue('Beispielstadt');
  await page.getByLabel(/Phone|Telefon/i).fill('+49 40 654321');
  await page.locator('form').getByRole('button', { name: /Speichern|Save/i }).click();
  await page.goto('/index.php?option=com_users&view=profile&layout=edit');
  await expect(page.getByLabel(/Phone|Telefon/i)).toHaveValue('+49 40 654321');
  diagnostics.expectClean();
});
