const { test, expect } = require('@playwright/test');
const { authenticateAdministrator, installDiagnostics } = require('../support/browser');

test('FDShop customer profile plugin configuration loads and saves', async ({ page, context, baseURL }, testInfo) => {
  const diagnostics = await installDiagnostics(page, baseURL);
  await authenticateAdministrator(page, context, testInfo);
  const extensionId = process.env.FDSHOP_PROFILE_PLUGIN_ID;
  expect(extensionId).toMatch(/^\d+$/);
  await page.goto(`/administrator/index.php?option=com_plugins&task=plugin.edit&extension_id=${extensionId}`);
  const statisticsNo = page.getByRole('button', { name: 'No', exact: true });
  if (await statisticsNo.isVisible()) await statisticsNo.click();
  await page.getByRole('tab', { name: /FDShop customer details|FDShop Kundendaten/i }).click();
  const company = page.locator('#jform_params_field_company');
  const street = page.locator('#jform_params_field_street');
  const firstOrder = page.locator('#jform_params_order_first_name');
  await expect(company).toHaveValue('1');
  await expect(street).toHaveValue('2');
  await expect(firstOrder).toHaveValue('10');
  await company.selectOption('2');
  await firstOrder.fill('15');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.locator('#system-message-container')).toContainText(/saved|gespeichert/i);
  await expect(company).toHaveValue('2');
  await expect(firstOrder).toHaveValue('15');
  await company.selectOption('1');
  await firstOrder.fill('10');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(company).toHaveValue('1');
  await expect(firstOrder).toHaveValue('10');
  const userId = process.env.FDSHOP_PROFILE_USER_ID;
  expect(userId).toMatch(/^\d+$/);
  await page.goto(`/administrator/index.php?option=com_users&task=user.edit&id=${userId}`);
  if (await statisticsNo.isVisible()) await statisticsNo.click();
  await page.getByRole('tab', { name: /FDShop customer details|FDShop Kundendaten|PLG_USER_FDSHOPPROFILE_FIELDSET_LABEL/i }).click();
  await expect(page.getByLabel(/First name|Vorname/i)).toBeVisible();
  await expect(page.getByLabel(/Street|Straße/i)).toBeVisible();
  await expect(page.getByLabel(/Phone|Telefon/i)).toBeVisible();
  diagnostics.expectClean();
});
