<?php
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Factory;
use FDShop\Component\FDShop\Administrator\Helper\DisplayDateHelper;
$order=$this->item;$products=$this->availableProducts??[];$shipments=$this->availableShipments??[];
$userLink=!empty($order->user_id)?Route::_('index.php?option=com_users&task=user.edit&id='.(int)$order->user_id):'';
$this->getDocument()->getWebAssetManager()->useScript('com_fdshop.admin-order');
$tokenName=Factory::getApplication()->getSession()->getFormToken();
?>
<form action="<?php echo Route::_('index.php?option=com_fdshop&view=order&id='.(int)$order->id); ?>" method="post" name="adminForm" id="adminForm" data-fdshop-order-draft>
<div class="row">
 <div class="col-12 col-xl-6"><div class="card mb-3"><div class="card-header">Bestell-Kopf</div><div class="card-body">
  <div class="mb-3"><strong>Bestellnummer</strong><div><?php echo $this->escape((string)$order->order_number); ?></div></div><div class="mb-3"><strong>Statusname</strong><div><?php echo $this->escape((string)$order->status_name); ?></div></div><div class="mb-3"><strong>Datum</strong><div><?php echo DisplayDateHelper::dateTime($order->created); ?></div></div><div><strong>Gesamtbetrag</strong><div><?php echo number_format((float)$order->grand_total,2,',','.'); ?> <?php echo $this->escape((string)$order->currency); ?></div></div>
 </div></div></div>
 <div class="col-12 col-xl-6"><div class="card mb-3"><div class="card-header">Kunde</div><div class="card-body">
  <div class="mb-2"><strong>Name</strong><div><?php if($userLink):?><a href="<?php echo $userLink; ?>"><?php endif; ?><?php echo $this->escape((string)$order->customer_name); ?><?php if($userLink):?></a><?php endif; ?></div></div><div class="mb-2"><strong>Historische E-Mail</strong><div><?php echo $this->escape((string)($order->customer_email??'Historisch unbekannt')); ?></div></div><div class="mb-2"><strong>Vorname / Nachname</strong><div><?php echo $this->escape(trim((string)$order->customer_first_name.' '.(string)$order->customer_last_name)?:'Historisch unbekannt'); ?></div></div><div class="mb-2"><strong>Firma</strong><div><?php echo $this->escape((string)($order->customer_company??'–')); ?></div></div><div class="mb-2"><strong>Anschrift</strong><div><?php echo $this->escape((string)($order->customer_street??'Historisch unbekannt')); ?><br><?php echo $this->escape(trim((string)$order->customer_postal_code.' '.(string)$order->customer_city)); ?><br><?php echo $this->escape((string)$order->customer_country); ?></div></div><div><strong>Telefon</strong><div><?php echo $this->escape((string)($order->customer_phone??'–')); ?></div></div>
 </div></div></div>
</div>
<div class="card mb-3"><div class="card-header">Checkout-Snapshot</div><div class="card-body row g-3">
 <div class="col-md-4"><strong>Zahlungsart</strong><div><?php echo $this->escape((string)($order->payment_method_name??'Historisch unbekannt')); ?> · <?php echo number_format((float)$order->payment_fee,2,',','.'); ?></div></div>
 <div class="col-md-4"><label for="jform_shipment_id" class="form-label fw-bold">Abholung/Versand</label><select name="shipment_id" id="jform_shipment_id" class="form-select"><?php $found=false;foreach($shipments as $shipment):$selected=(int)$shipment->id===(int)$order->shipment_id;$found=$found||$selected;?><option value="<?php echo (int)$shipment->id; ?>"<?php echo $selected?' selected':''; ?>><?php echo $this->escape((string)$shipment->shipment_name); ?> · <?php echo number_format((float)$shipment->shipment_price,2,',','.'); ?></option><?php endforeach; ?><?php if(!$found):?><option value="<?php echo (int)$order->shipment_id; ?>" selected><?php echo $this->escape((string)$order->shipment_name); ?> · <?php echo number_format((float)$order->shipment_fee,2,',','.'); ?> [historisch]</option><?php endif; ?></select></div>
 <div class="col-md-4"><strong>Lagerzustand</strong><div><?php echo $this->escape((string)($order->stock_state??'Historisch unbekannt')); ?></div></div><div class="col-md-4"><strong>Gutschein</strong><div><?php echo $this->escape((string)($order->coupon_code??'–')); ?> · -<?php echo number_format((float)$order->coupon_discount,2,',','.'); ?></div></div><div class="col-md-4"><strong>AGB</strong><div><?php echo (int)$order->terms_required===1?'erforderlich · ':''; ?><?php echo (int)$order->terms_accepted===1?'bestätigt':'nicht bestätigt'; ?></div></div><div class="col-12"><strong>Bestellbemerkung</strong><div><?php echo nl2br($this->escape((string)$order->order_note)); ?></div></div><?php if(!empty($order->mail_warning)):?><div class="col-12 alert alert-warning"><?php echo $this->escape((string)$order->mail_warning); ?></div><?php endif; ?>
</div></div>
<?php if($this->openShipmentRequest):?><div class="card mb-3 border-warning"><div class="card-header bg-warning-subtle">Offene Abholstationsanfrage</div><div class="card-body"><p><strong>Aktuell:</strong> <?php echo $this->escape((string)$this->openShipmentRequest->current_shipment_name); ?><br><strong>Gewünscht:</strong> <?php echo $this->escape((string)$this->openShipmentRequest->requested_shipment_name); ?><br><strong>Eingegangen:</strong> <?php echo DisplayDateHelper::dateTime($this->openShipmentRequest->created); ?></p><button class="btn btn-outline-success" type="submit" onclick="this.form.task.value='order.resolveShipmentRequest'">Als erledigt markieren</button></div></div><?php endif; ?>
<div class="card mb-3"><div class="card-header">Widerruf</div><div class="card-body">
<?php $withdrawalLabels=['none'=>'Nicht erklärt','declared'=>'Eingegangen','accepted'=>'Akzeptiert','rejected'=>'Abgelehnt'];$withdrawal=(string)($order->withdrawal_status??'none'); ?>
<p><strong>Status:</strong> <?php echo $this->escape($withdrawalLabels[$withdrawal]??$withdrawal); ?><?php if(!empty($order->withdrawal_declared_at)):?><br><strong>Erklärt:</strong> <?php echo DisplayDateHelper::dateTime($order->withdrawal_declared_at); ?><?php endif; ?><?php if(!empty($order->withdrawal_decision_text)):?><br><strong>Entscheidung:</strong> <?php echo nl2br($this->escape((string)$order->withdrawal_decision_text)); ?><?php endif; ?></p>
<?php if($withdrawal==='declared'):?><div class="d-flex flex-wrap gap-2 align-items-end"><button class="btn btn-success" type="submit" onclick="this.form.task.value='order.withdrawalAccept'">Widerruf bestätigen</button><div class="flex-grow-1"><label class="form-label" for="withdrawal_reason">Individuelle Ablehnungsbegründung</label><textarea class="form-control" id="withdrawal_reason" name="withdrawal_reason" rows="2"></textarea></div><button class="btn btn-danger" type="submit" onclick="this.form.task.value='order.withdrawalReject'">Widerruf ablehnen</button></div><?php endif; ?>
</div></div>
<div class="card mb-3"><div class="card-header">Bestellpositionen</div><div class="card-body"><div class="table-responsive"><table class="table table-striped align-middle" data-order-items><thead><tr><th>Produktname</th><th>SKU</th><th>Menge</th><th>Einzelpreis (Brutto)</th><th>Gesamtpreis Position</th><th>Aktion</th></tr></thead><tbody>
<?php foreach($this->orderItems as $item):?><tr class="<?php echo $item->is_removed?'table-secondary text-muted':''; ?>" data-order-item-row><td><?php echo $this->escape((string)$item->product_name); ?> <?php if($item->is_removed):?><span class="badge bg-secondary">Entfernt</span><?php endif; ?><div class="small text-muted"><?php echo $this->escape((string)($item->manufacturer_name?:'Historischer Hersteller unbekannt')); ?></div></td><td><?php echo $this->escape((string)$item->sku); ?><div class="small text-muted">GTIN: <?php echo $this->escape((string)($item->gtin?:'historisch unbekannt')); ?></div></td><td><?php if(!$item->is_removed):?><input type="number" name="items[<?php echo (int)$item->id; ?>][quantity]" class="form-control" min="1" step="1" value="<?php echo $this->escape((string)(float)$item->quantity); ?>"><?php else:?><?php echo $this->escape((string)$item->quantity); ?><?php endif; ?></td><td><?php echo number_format((float)$item->unit_price_gross,2,',','.'); ?> <?php echo $this->escape((string)$item->currency); ?><div class="small text-muted">Regulär: <?php echo number_format((float)$item->regular_price_gross,2,',','.'); ?> · Aktion: <?php echo number_format((float)$item->discount_price_gross,2,',','.'); ?> · MwSt.: <?php echo number_format((float)$item->tax_rate,2,',','.'); ?> %</div></td><td><?php echo number_format((float)$item->line_total_gross,2,',','.'); ?> <?php echo $this->escape((string)$item->currency); ?></td><td><?php if(!$item->is_removed):?><input type="hidden" name="items[<?php echo (int)$item->id; ?>][removed]" value="0" data-removed><button type="button" class="btn btn-outline-danger btn-sm" data-remove-existing>Entfernen</button><?php else:?><span class="small">Historisch erhalten</span><?php endif; ?></td></tr><?php endforeach; ?>
</tbody></table></div></div></div>
<?php if($this->orderBundles):?>
<div class="card mb-3" data-order-bundles><div class="card-header">Bestellte Bundles</div><div class="card-body">
<p class="text-muted">Bundles sind unveränderliche Bestellsnapshots. Ihre enthaltenen Produkte können nicht einzeln bearbeitet oder entfernt werden.</p>
<?php foreach($this->orderBundles as $bundle):?>
<section class="border rounded mb-3 <?php echo $bundle->is_removed?'bg-light text-muted':''; ?>" data-order-bundle="<?php echo (int)$bundle->id; ?>">
 <div class="p-3 border-bottom d-flex flex-wrap justify-content-between gap-3"><div><h3 class="h5 mb-1"><?php echo $this->escape((string)$bundle->bundle_name); ?> <?php if($bundle->is_removed):?><span class="badge bg-secondary">Entfernt</span><?php endif;?></h3><span class="text-muted">Bundle-Nr. <?php echo $this->escape((string)$bundle->bundle_number); ?></span></div><div class="text-end"><strong><?php echo number_format((float)$bundle->total_gross,2,',','.'); ?> <?php echo $this->escape((string)$order->currency); ?></strong><div class="small text-muted"><?php echo number_format((float)$bundle->quantity_items,0,',','.'); ?> Artikel<?php if((float)$bundle->discount_percent>0):?> · <?php echo number_format((float)$bundle->discount_percent,2,',','.'); ?> % Bundle-Rabatt (<?php echo number_format((float)$bundle->discount_amount_gross,2,',','.'); ?> <?php echo $this->escape((string)$order->currency); ?>)<?php endif;?></div></div></div>
 <div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Produkt</th><th>SKU</th><th>Menge</th><th>Einzelpreis</th><th>Snapshot-Gesamt</th><th>Status</th></tr></thead><tbody><?php foreach($bundle->items as $item):?><tr class="<?php echo $item->is_removed?'table-secondary text-muted':''; ?>"><td><?php echo $this->escape((string)$item->product_name); ?></td><td><?php echo $this->escape((string)$item->sku); ?></td><td><?php echo $this->escape((string)(float)$item->quantity); ?></td><td><?php echo number_format((float)$item->unit_price_gross,2,',','.'); ?> <?php echo $this->escape((string)$item->currency); ?></td><td><?php echo number_format((float)$item->total_gross,2,',','.'); ?> <?php echo $this->escape((string)$item->currency); ?></td><td><?php echo $item->is_removed?'Historisch entfernt':'Bestandteil des Bundles'; ?></td></tr><?php endforeach;?></tbody></table></div>
</section>
<?php endforeach;?>
</div></div>
<?php endif;?>
<div class="card mb-3"><div class="card-header">Neues Produkt hinzufügen</div><div class="card-body"><div class="row g-3 align-items-end"><div class="col-12 col-xl-7"><label for="jform_product_id" class="form-label">Produktauswahl</label><select id="jform_product_id" class="form-select"><option value="">- Produkt wählen -</option><?php foreach($products as $product):?><option value="<?php echo (int)$product->id; ?>" data-name="<?php echo $this->escape((string)$product->product_name); ?>" data-sku="<?php echo $this->escape((string)$product->sku); ?>"<?php echo empty($product->is_active)?' disabled':''; ?>><?php echo $this->escape((string)$product->product_name.' ('.(string)$product->sku.')'.(empty($product->is_active)?' [inaktiv]':'')); ?></option><?php endforeach; ?></select></div><div class="col-12 col-md-4 col-xl-3"><label for="jform_quantity" class="form-label">Menge</label><input type="number" id="jform_quantity" class="form-control" min="1" step="1" value="1"></div><div class="col-12 col-md-8 col-xl-2"><button type="button" class="btn btn-success w-100" data-add-draft>Hinzufügen</button></div></div><div class="mt-3" data-new-items aria-live="polite"></div><p class="small text-muted mt-2 mb-0">Entwurfsänderungen werden erst über die Joomla-Toolbar „Speichern“ übernommen.</p></div></div>
<div class="card mb-3"><div class="card-header">Summenblock</div><div class="card-body"><strong>Gesamtbetrag</strong><div><?php echo number_format((float)$order->grand_total,2,',','.'); ?> <?php echo $this->escape((string)$order->currency); ?></div><div class="small text-muted">Die endgültige Summe wird beim Speichern serverseitig berechnet.</div></div></div>
<div class="card mb-3"><div class="card-header">Dokumente</div><div class="card-body d-flex gap-2 flex-wrap">
<?php if($this->customerDocuments):?><?php foreach($this->customerDocuments as $document):?><a class="btn btn-outline-primary" href="<?php echo Route::_('index.php?option=com_fdshop&task=order.downloadConfirmation&id='.(int)$order->id.'&document_id='.(int)$document->id.'&'.$tokenName.'=1'); ?>"><span class="icon-file-pdf" aria-hidden="true"></span> <?php echo $this->escape((int)$document->version_no===0?'Original':'Version '.sprintf('%02d',(int)$document->version_no)); ?></a><?php endforeach;?><?php elseif(!empty($order->confirmation_pdf_path)):?><a class="btn btn-outline-primary" href="<?php echo Route::_('index.php?option=com_fdshop&task=order.downloadConfirmation&id='.(int)$order->id.'&'.$tokenName.'=1'); ?>"><span class="icon-file-pdf" aria-hidden="true"></span> Kunden-Bestellbestätigung (Legacy)</a><?php else:?><span class="text-muted align-self-center">Keine archivierte Kunden-Bestellbestätigung vorhanden (Legacy oder Versandfehler).</span><?php endif; ?>
<a class="btn btn-outline-secondary" href="<?php echo Route::_('index.php?option=com_fdshop&task=order.downloadPackingList&id='.(int)$order->id.'&'.$tokenName.'=1'); ?>"><span class="icon-print" aria-hidden="true"></span> Packliste erzeugen</a>
</div></div>
<?php if($this->statusHistory):?><div class="card mb-3"><div class="card-header">Status-Historie</div><div class="card-body"><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Datum</th><th>Alter Status</th><th>Neuer Status</th><th>Benutzer / Kommentar</th></tr></thead><tbody><?php foreach($this->statusHistory as $entry):?><tr><td><?php echo DisplayDateHelper::dateTime($entry->changed_at); ?></td><td><?php echo $this->escape((string)$entry->old_status_name); ?></td><td><?php echo $this->escape((string)$entry->new_status_name); ?></td><td><?php echo $this->escape((string)($entry->changed_by_name?:'ID '.(int)$entry->changed_by)); ?><br><span class="small text-muted"><?php echo $this->escape((string)$entry->comment); ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div><?php endif; ?>
<?php if($this->orderHistory):?><div class="card mb-3"><div class="card-header">Allgemeine Historie</div><div class="card-body"><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Titel</th><th>Text</th><th>Datum</th><th>Benutzer</th></tr></thead><tbody><?php foreach($this->orderHistory as $entry):?><tr><td><?php echo $this->escape((string)$entry->event_title); ?></td><td><?php echo nl2br($this->escape((string)$entry->event_text)); ?></td><td><?php echo DisplayDateHelper::dateTime($entry->created); ?></td><td><?php echo $this->escape((string)($entry->created_by_name?:'ID '.(int)$entry->created_by)); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div><?php endif; ?>
<input type="hidden" name="id" value="<?php echo (int)$order->id; ?>"><input type="hidden" name="expected_modified" value="<?php echo $this->escape((string)($order->modified?:$order->created)); ?>"><input type="hidden" name="task" value="order.save"><?php echo HTMLHelper::_('form.token'); ?>
</form>
