<?php
defined('_JEXEC') or die;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Session\Session;
$token=Session::getFormToken();
?>
<main class="fdshop-favorites-page" data-favorites-page data-token="<?php echo$token;?>" data-create-url="<?php echo Route::_('index.php?option=com_fdshop&task=favorite.createList&format=json');?>" data-rename-url="<?php echo Route::_('index.php?option=com_fdshop&task=favorite.renameList&format=json');?>" data-delete-url="<?php echo Route::_('index.php?option=com_fdshop&task=favorite.deleteList&format=json');?>"><header><h1>Meine Favoriten</h1><p>Deine gespeicherten Produkte sind auf allen deinen Geräten verfügbar.</p></header><div class="fdshop-favorites-page__toolbar"><nav aria-label="Favoritenlisten"><?php foreach($this->lists as$list):?><a class="btn <?php echo(int)$list->id===$this->selected?'btn-primary':'btn-outline-primary';?>" href="<?php echo Route::_('index.php?option=com_fdshop&view=favorites&list_id='.(int)$list->id);?>"><?php echo htmlspecialchars($list->name,ENT_QUOTES,'UTF-8');?> <small>(<?php echo(int)$list->product_count;?>)</small></a><?php endforeach;?></nav><form data-favorite-create><label for="favorite-list-name">Neue Liste</label><input id="favorite-list-name" name="name" maxlength="100" required><button class="btn btn-secondary">Anlegen</button></form></div><?php foreach($this->lists as$list)if((int)$list->id===$this->selected&&(int)$list->is_default===0):?><div class="fdshop-favorites-page__manage"><button type="button" class="btn btn-sm btn-outline-secondary" data-favorite-rename data-list-id="<?php echo(int)$list->id;?>" data-name="<?php echo htmlspecialchars($list->name,ENT_QUOTES,'UTF-8');?>">Liste umbenennen</button><button type="button" class="btn btn-sm btn-outline-danger" data-favorite-delete data-list-id="<?php echo(int)$list->id;?>">Liste löschen</button></div><?php endif;?><?php if(!$this->items):?><div class="fdshop-favorites-page__empty"><h2>Noch keine Favoriten in dieser Liste</h2><p>Markiere Produkte mit dem Herz, um sie hier dauerhaft zu speichern.</p></div><?php else:?><div class="fdshop-products"><?php foreach($this->items as$item)echo LayoutHelper::render('product.card',['item'=>$item,'purchaseEnabled'=>$this->purchaseEnabled,'favoriteEnabled'=>true,'favoriteGuest'=>false,'favoriteActive'=>true],JPATH_COMPONENT_SITE.'/layouts');?></div><?php endif;?></main>
<script>document.addEventListener('DOMContentLoaded',function(){var root=document.querySelector('[data-favorites-page]');if(!root)return;function post(url,data){data[root.dataset.token]='1';return fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body:new URLSearchParams(data)}).then(function(r){return r.json();}).then(function(r){if(r.success===false)throw new Error(r.message);return r;});}var form=root.querySelector('[data-favorite-create]');form.addEventListener('submit',function(e){e.preventDefault();post(root.dataset.createUrl,{name:new FormData(form).get('name')}).then(function(){location.reload();}).catch(function(e){alert(e.message);});});root.addEventListener('click',function(e){var rename=e.target.closest('[data-favorite-rename]'),del=e.target.closest('[data-favorite-delete]');if(rename){var name=prompt('Neuer Listenname',rename.dataset.name);if(name)post(root.dataset.renameUrl,{list_id:rename.dataset.listId,name:name}).then(function(){location.reload();}).catch(function(e){alert(e.message);});}if(del&&confirm('Diese Favoritenliste löschen?'))post(root.dataset.deleteUrl,{list_id:del.dataset.listId}).then(function(){location.href='index.php?option=com_fdshop&view=favorites';}).catch(function(e){alert(e.message);});});});</script>
