<?php
defined('_JEXEC') or die;
$o=$displayData['order'];$c=$displayData['config'];$h=$displayData['helper'];
$rows=[];foreach($displayData['items'] as $item)$rows[]=$item;foreach($displayData['bundles'] as $bundle)$rows[]=(object)['document_image_path'=>'','sku'=>$bundle->bundle_number,'product_name'=>$bundle->bundle_name,'regular_price_gross'=>$bundle->subtotal_gross,'unit_price_gross'=>$bundle->total_gross,'quantity'=>1,'line_total_gross'=>$bundle->total_gross,'currency'=>$o->currency];
$logo=$h->image((string)($c->document_company_logo??''));
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Bestellbestätigung (Kunde)</title><style>
@page{margin:15mm 12mm 31mm}body{font-family:DejaVu Sans,sans-serif;font-size:8.7pt;color:#111}.header{width:100%;border-collapse:collapse}.header td{width:50%;vertical-align:top}.header h1{font-size:17pt;font-weight:400;margin:0 0 18mm;white-space:nowrap}.company{text-align:right;line-height:1.35}.company img{max-width:45mm;max-height:22mm;display:block;margin-left:auto;margin-bottom:2mm}.address{line-height:1.45}.meta{margin:9mm 0 5mm;line-height:1.55}.shipment{display:table;background:#ddd;padding:2.5mm 4mm;font-size:12pt;line-height:1.2;max-width:92mm}.items{width:100%;border-collapse:collapse;table-layout:fixed}.items thead{display:table-header-group}.items tr{page-break-inside:avoid}.items th,.items td{padding:2mm 1mm;border-bottom:.2mm solid #ccc;vertical-align:middle;overflow-wrap:anywhere}.items th{white-space:nowrap}.items .alt{background:#eef2f8}.items img{max-width:11mm;max-height:11mm}.items .image{width:10%}.items .sku{width:12%}.items .product{width:34%}.items .price{width:13%;text-align:right}.items .quantity{width:7%;text-align:center}.items .discount{width:11%;text-align:right}.items .amount{width:13%;text-align:right}.sums{width:46%;margin:5mm 0 0 auto;border-collapse:collapse}.sums td{padding:1.2mm}.sums td:last-child{text-align:right;white-space:nowrap}.sums .total{font-weight:bold;font-size:12pt;border-top:.4mm solid #333}.payment{text-align:right}.page-footer{position:fixed;left:0;right:0;bottom:-25mm;height:23mm}.thanks{text-align:center;font-weight:bold;border-bottom:.3mm solid #aaa;padding-bottom:2mm}.footer{width:100%;font-size:6.8pt;margin-top:2mm;border-collapse:collapse}.footer td{width:33%;vertical-align:top}
</style></head><body>
<table class="header"><tr><td><h1>Bestellbestätigung (Kunde)</h1><div class="address"><b>Rechnungsadresse:</b><br><?php if($o->customer_company):?><?= $h->e($o->customer_company) ?><br><?php endif;?><?= $h->e(trim($o->customer_first_name.' '.$o->customer_last_name)) ?><br><?= $h->e($o->customer_street) ?><br><?= $h->e($h->addressLine((string)$o->customer_postal_code,(string)$o->customer_city)) ?><?php if($o->customer_country):?><br><?= $h->e($o->customer_country) ?><?php endif;?></div></td><td><div class="company"><?= $logo ?><b><?= $h->e($c->document_company_name??'FDShop') ?></b><br><?= $h->e($c->document_company_street??'') ?><br><?= $h->e($h->addressLine((string)($c->document_company_postal_code??''),(string)($c->document_company_city??''))) ?><br><br><?= $h->e($c->document_company_phone??'') ?><br><?= $h->e($c->document_company_email??'') ?><br><?= $h->e($c->document_company_website??'') ?></div></td></tr></table>
<div class="meta"><b>Bestelldatum:</b> <?= $h->date($o->created) ?><br><b>Bestellnummer:</b> <?= $h->e($o->order_number) ?><br><span class="shipment">Abholstation „<?= $h->e($o->shipment_name) ?>“</span></div>
<table class="items"><colgroup><col class="image"><col class="sku"><col class="product"><col class="price"><col class="quantity"><col class="discount"><col class="amount"></colgroup><thead><tr><th>Bild</th><th>Art.-Nr.</th><th>Produkt</th><th class="price">Einzelpreis</th><th class="quantity">Menge</th><th class="discount">Rabatt</th><th class="amount">Betrag</th></tr></thead><tbody>
<?php foreach($rows as $n=>$item):$currency=(string)($item->currency??$o->currency);$regular=(float)$item->regular_price_gross;$effective=(float)$item->unit_price_gross;$discount=max(0,$regular-$effective);?><tr<?= $n%2?' class="alt"':''?>><td><?= $h->image((string)($item->document_image_path??''),40) ?></td><td><?= $h->e($item->sku) ?></td><td><?= $h->e($item->product_name) ?></td><td class="price"><?php if($discount>0):?><s><?= $h->money($regular,$currency) ?></s><br><?php endif;?><?= $h->money($effective,$currency) ?></td><td class="quantity"><?= $h->qty($item->quantity) ?></td><td class="discount"><?= $discount>0?$h->money($discount,$currency):'-' ?></td><td class="amount"><?= $h->money($item->line_total_gross,$currency) ?></td></tr><?php endforeach;?>
</tbody></table>
<table class="sums"><tr><td>Zwischensumme</td><td><?= $h->money($o->subtotal,$o->currency) ?></td></tr><?php if((float)$o->coupon_discount>0):?><tr><td>Gutschein<?= $o->coupon_code?' ('.$h->e($o->coupon_code).')':'' ?></td><td>- <?= $h->money($o->coupon_discount,$o->currency) ?></td></tr><?php endif;?><?php if((float)$o->shipment_fee>0):?><tr><td>Versand/Abholung</td><td><?= $h->money($o->shipment_fee,$o->currency) ?></td></tr><?php endif;?><?php if((float)$o->payment_fee>0):?><tr><td>Zahlungsgebühr</td><td><?= $h->money($o->payment_fee,$o->currency) ?></td></tr><?php endif;?><tr class="total"><td>Gesamtbetrag</td><td><?= $h->money($o->grand_total,$o->currency) ?></td></tr></table>
<?php if(preg_match('/überweisung|bank/i',(string)$o->payment_method_name)):?><p class="payment">Bitte überweisen Sie den Gesamtbetrag innerhalb von <?= max(1,(int)($c->document_payment_days??7)) ?> Tagen.</p><?php endif;?>
<div class="page-footer"><div class="thanks">Vielen Dank für Ihren Einkauf bei <?= $h->e($c->document_company_name??'FDShop') ?></div><table class="footer"><tr><td><b>Bankverbindung:</b><br>Kontoinhaber: <?= $h->e($c->document_account_holder??'') ?><br>Bankname: <?= $h->e($c->document_bank_name??'') ?></td><td>IBAN: <?= $h->e($c->document_iban??'') ?><br>BIC/SWIFT: <?= $h->e($c->document_bic??'') ?></td><td><?= $h->e(strip_tags((string)($c->document_footer_text??''))) ?></td></tr></table></div>
</body></html>
