<?php
defined('_JEXEC') or die;
$o=$displayData['order'];$c=$displayData['config'];$h=$displayData['helper'];$groups=[1=>[],2=>[]];
foreach(array_merge($displayData['items'],$displayData['bundleItems']) as $item){$g=(int)($item->packing_group??0);if(!$g)$g=$h->currentPackingGroup((int)$item->product_id,(int)($c->document_special_category_id??0));$groups[$g===2?2:1][]=$item;}
$color=$h->safeColor((string)($displayData['shipment']->shipment_color??''));$text=$h->contrastColor($color);$logo=$h->image((string)($c->document_company_logo??''));
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Packliste</title><style>
@page{margin:14mm 12mm 14mm}body{font-family:DejaVu Sans,sans-serif;font-size:8.5pt;color:#111}.header{width:100%;border-collapse:collapse}.header td{width:50%;vertical-align:top}.header h1{font-size:17pt;font-weight:400;margin:0 0 7mm;white-space:nowrap}.company{text-align:right;line-height:1.3}.company img{max-width:42mm;max-height:20mm;display:block;margin-left:auto;margin-bottom:2mm}.address{line-height:1.4}.order-meta{margin-top:4mm}.shipping-wrap{text-align:right;margin:4mm 0}.shipping{display:inline-block;text-align:left;width:46%;padding:3mm;font-size:9.5pt;line-height:1.45}.remark,.notes{border:.3mm solid #999;padding:3mm;margin:4mm 0}.notes{height:15mm}.collection{page-break-inside:auto}.collection h2{font-size:13pt;margin:6mm 0 2mm}.items{width:100%;border-collapse:collapse;table-layout:fixed}.items thead{display:table-header-group}.items tr{page-break-inside:avoid}.items th,.items td{font-size:7.7pt;padding:2mm .8mm;border-bottom:.2mm solid #ccc;vertical-align:middle;overflow-wrap:anywhere}.items .alt{background:#eef2f8}.items img{max-width:10mm;max-height:10mm}.items .image{width:9%}.items .sku{width:12%}.items .product{width:34%}.items .category{width:18%;text-align:center}.items .quantity{width:8%;text-align:center}.items .check{width:9.5%;text-align:center}.box{font-family:DejaVu Sans;font-size:16pt;line-height:1}.empty{border-bottom:.2mm solid #ccc;padding:2mm}
</style></head><body>
<table class="header"><tr><td><h1>Bestellbestätigung (Firma)</h1><div class="address"><?php if($o->customer_company):?><?= $h->e($o->customer_company) ?><br><?php endif;?><?= $h->e(trim($o->customer_first_name.' '.$o->customer_last_name)) ?><br><?= $h->e($o->customer_street) ?><br><?= $h->e($h->addressLine((string)$o->customer_postal_code,(string)$o->customer_city)) ?></div><div class="order-meta">Bestellnummer: <?= $h->e($o->order_number) ?><br>Bestelldatum: <?= $h->date($o->created) ?></div></td><td><div class="company"><?= $logo ?><b><?= $h->e($c->document_company_name??'FDShop') ?></b><br><?= $h->e($c->document_company_street??'') ?><br><?= $h->e($h->addressLine((string)($c->document_company_postal_code??''),(string)($c->document_company_city??''))) ?></div></td></tr></table>
<div class="shipping-wrap"><div class="shipping" style="background:<?= $color ?>;color:<?= $text ?>"><b>Versandinformationen:</b><br>Käufergruppe: __________________<br>Abholstation „<?= $h->e($o->shipment_name) ?>“<br><span class="box">□</span> Gepackt: Paketanzahl __________</div></div>
<div class="remark"><b>Bemerkung Käufer:</b> <?= trim((string)$o->order_note)!==''?nl2br($h->e($o->order_note)):'Keine Bemerkung' ?></div><div class="notes"><b>Notizen:</b></div>
<?php foreach([1,2] as $group):$title=$group===1?($c->document_collection_one_title??'Sammlung 1'):($c->document_collection_two_title??'Sammlung 2');?><section class="collection"><h2><?= $h->e($title) ?></h2><?php if($groups[$group]):?><table class="items"><colgroup><col class="image"><col class="sku"><col class="product"><col class="category"><col class="quantity"><col class="check"><col class="check"></colgroup><thead><tr><th>Bild</th><th>Art.-Nr.</th><th>Produkt</th><th class="category">Kategorie</th><th class="quantity">Anzahl</th><th class="check">Gerichtet</th><th class="check">Gepackt</th></tr></thead><tbody><?php foreach($groups[$group] as $n=>$item):?><tr<?= $n%2?' class="alt"':''?>><td><?= $h->image((string)($item->document_image_path??''),36) ?></td><td><?= $h->e($item->sku) ?></td><td><?= $h->e($item->product_name) ?></td><td class="category"><?= $group===2?'Verbundfeuerwerk':'Alle außer Verbünde' ?></td><td class="quantity"><?= $h->qty($item->quantity) ?></td><td class="check"><span class="box">□</span></td><td class="check"><span class="box">□</span></td></tr><?php endforeach;?></tbody></table><?php else:?><p class="empty">Keine Positionen</p><?php endif;?></section><?php endforeach;?>
</body></html>
