<?php
namespace FDShop\Component\FDShop\Site\Service;
defined('_JEXEC') or die;

use FDShop\Component\FDShop\Administrator\Service\BuyerEligibilityServiceInterface;
use FDShop\Component\FDShop\Administrator\Service\OrderServiceInterface;
use FDShop\Component\FDShop\Administrator\Service\WatchlistServiceInterface;
use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Factory;
use Joomla\CMS\Plugin\PluginHelper;
use Joomla\CMS\Uri\Uri;
use Joomla\CMS\User\UserFactoryInterface;
use Joomla\Database\DatabaseInterface;
use Joomla\Registry\Registry;

final class AccountService implements AccountServiceInterface
{
    public function __construct(private readonly DatabaseInterface $db, private readonly BuyerEligibilityServiceInterface $eligibility, private readonly OrderServiceInterface $orders, private readonly WatchlistServiceInterface $watchlist) {}

    public function dashboard(int $userId, int $page = 1, ?int $orderId = null): array
    {
        $this->user($userId); $limit=10; $page=max(1,$page); $offset=($page-1)*$limit;
        $q=$this->db->getQuery(true)->select('COUNT(*)')->from($this->db->quoteName('#__fdshop_orders'))->where('user_id='.(int)$userId);$this->db->setQuery($q);$total=(int)$this->db->loadResult();
        $q=$this->db->getQuery(true)->select(['o.id','o.order_number','o.created','o.modified','o.order_status','o.grand_total','o.currency','o.shipment_id','o.shipment_name','o.payment_method_name','o.withdrawal_status','o.withdrawal_declared_at','o.withdrawal_decision_text','s.status_name','sr.id AS open_shipment_request_id'])->from($this->db->quoteName('#__fdshop_orders','o'))->leftJoin($this->db->quoteName('#__fdshop_order_statuses','s').' ON s.id=o.order_status_id')->leftJoin($this->db->quoteName('#__fdshop_order_shipment_requests','sr')." ON sr.order_id=o.id AND sr.status='open'")->where('o.user_id='.(int)$userId)->order('o.created DESC');$this->db->setQuery($q,$offset,$limit);$orders=(array)$this->db->loadObjectList();
        $selected=null;$items=[];$bundles=[];
        if($orderId){$selected=$this->ownedOrder($userId,$orderId);$q=$this->db->getQuery(true)->select('*')->from($this->db->quoteName('#__fdshop_order_items'))->where('order_id='.(int)$orderId)->where('is_removed=0')->order('id');$this->db->setQuery($q);$items=(array)$this->db->loadObjectList();$q=$this->db->getQuery(true)->select('*')->from($this->db->quoteName('#__fdshop_order_bundles'))->where('order_id='.(int)$orderId)->where('is_removed=0')->order('id');$this->db->setQuery($q);$bundles=(array)$this->db->loadObjectList();if($bundles!==[]){$bundleIds=array_map(static fn($bundle)=>(int)$bundle->id,$bundles);$q=$this->db->getQuery(true)->select('*')->from($this->db->quoteName('#__fdshop_order_bundle_items'))->where('order_bundle_id IN ('.implode(',',$bundleIds).')')->where('is_removed=0')->order('order_bundle_id,id');$this->db->setQuery($q);$grouped=[];foreach((array)$this->db->loadObjectList() as $bundleItem)$grouped[(int)$bundleItem->order_bundle_id][]=$bundleItem;foreach($bundles as $bundle)$bundle->items=$grouped[(int)$bundle->id]??[];}}
        $q=$this->db->getQuery(true)->select(['id','shipment_name'])->from($this->db->quoteName('#__fdshop_shipments'))->where('published=1')->order('ordering,id');$this->db->setQuery($q);$shipments=(array)$this->db->loadObjectList();
        $q=$this->db->getQuery(true)->select('*')->from($this->db->quoteName('#__fdshop_config'))->where('id=1');$this->db->setQuery($q);$config=$this->db->loadObject();
        $q=$this->db->getQuery(true)->select(['event_type','event_title','created'])->from($this->db->quoteName('#__fdshop_user_history'))->where('user_id='.(int)$userId)->order('created DESC');$this->db->setQuery($q,0,8);$history=(array)$this->db->loadObjectList();
        $lastF3Submission=null;foreach($history as $entry)if((string)$entry->event_type==='f3_documents_submitted'){$lastF3Submission=$entry->created;break;}
        return compact('orders','total','page','limit','selected','items','bundles','shipments','config','history','lastF3Submission')+['profile'=>$this->profile($userId),'profile_config'=>$this->profileConfiguration(),'user'=>$this->user($userId),'buyer_status'=>$this->eligibility->userStatus($userId),'username_change_allowed'=>(bool)ComponentHelper::getParams('com_users')->get('change_login_name',0),'watchlist'=>$this->watchlist->forUser($userId)];
    }

    public function removeWatch(int $userId, int $watchId): void { $this->watchlist->remove($userId, $watchId); }

    public function saveProfile(int $userId,array $profile):void
    {
        $fieldConfig=$this->profileConfiguration();$allowed=array_keys($fieldConfig['active']);$required=$fieldConfig['required'];$clean=[];foreach($allowed as $f){if(!$fieldConfig['active'][$f])continue;$clean[$f]=trim(strip_tags((string)($profile[$f]??'')));if(mb_strlen($clean[$f])>255)throw new \DomainException('Ein Kontaktdatenfeld ist zu lang.');}foreach($required as $f)if(($clean[$f]??'')==='')throw new \DomainException('Bitte füllen Sie alle erforderlichen Kontaktdaten aus.');
        $this->db->transactionStart();try{foreach($clean as $f=>$v){$key='fdshop_customer.'.$f;$q=$this->db->getQuery(true)->delete($this->db->quoteName('#__user_profiles'))->where('user_id='.(int)$userId)->where('profile_key='.$this->db->quote($key));$this->db->setQuery($q)->execute();$row=(object)['user_id'=>$userId,'profile_key'=>$key,'profile_value'=>json_encode($v,JSON_UNESCAPED_UNICODE),'ordering'=>100];$this->db->insertObject('#__user_profiles',$row);} $user=$this->user($userId);$user->name=trim($clean['first_name'].' '.$clean['last_name']);if(!$user->save())throw new \RuntimeException($user->getError()?:'Kontaktdaten konnten nicht gespeichert werden.');$this->history($userId,'profile_changed','Kontaktdaten geändert');$this->db->transactionCommit();}catch(\Throwable $e){$this->db->transactionRollback();throw $e;}
    }

    public function saveCredentials(int $userId,?string $username,?string $password):void
    {
        $user=$this->user($userId);$changed=[];
        if($username!==null&&trim($username)!==''&&trim($username)!==$user->username){if(!ComponentHelper::getParams('com_users')->get('change_login_name',0))throw new \DomainException('Der Benutzername kann laut Joomla-Konfiguration nicht geändert werden.');$user->username=trim($username);$changed[]=['username_changed','Benutzername geändert'];}
        if($password!==null&&$password!==''){$this->assertPasswordPolicy($password);if(!$user->bind(['password'=>$password,'password2'=>$password]))throw new \RuntimeException($user->getError());$changed[]=['password_changed','Passwort geändert'];}
        if($changed===[])return;if(!$user->save())throw new \RuntimeException($user->getError()?:'Kontodaten konnten nicht gespeichert werden.');foreach($changed as [$type,$title])$this->history($userId,$type,$title);
    }

    public function requestEmailChange(int $userId,string $email):void
    {
        $email=trim(mb_strtolower($email));if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new \DomainException('Bitte geben Sie eine gültige E-Mail-Adresse ein.');$q=$this->db->getQuery(true)->select('COUNT(*)')->from($this->db->quoteName('#__users'))->where('LOWER(email)='.$this->db->quote($email))->where('id<>'.(int)$userId);$this->db->setQuery($q);if((int)$this->db->loadResult()>0)throw new \DomainException('Diese E-Mail-Adresse wird bereits verwendet.');
        $token=bin2hex(random_bytes(32));$now=Factory::getDate();$expires=(clone $now)->modify('+2 hours')->toSql();$q=$this->db->getQuery(true)->delete($this->db->quoteName('#__fdshop_user_email_changes'))->where('user_id='.(int)$userId)->where('consumed_at IS NULL');$this->db->setQuery($q)->execute();$row=(object)['user_id'=>$userId,'new_email'=>$email,'token_hash'=>hash('sha256',$token),'expires_at'=>$expires,'created'=>$now->toSql()];$this->db->insertObject('#__fdshop_user_email_changes',$row);$url=Uri::root().'index.php?option=com_fdshop&task=account.verifyEmail&token='.rawurlencode($token);try{$this->mail($email,'FDShop: neue E-Mail-Adresse bestätigen','Bitte bestätigen Sie Ihre neue E-Mail-Adresse innerhalb von zwei Stunden:<br><a href="'.htmlspecialchars($url,ENT_QUOTES,'UTF-8').'">E-Mail-Adresse bestätigen</a>');}catch(\Throwable $e){$q=$this->db->getQuery(true)->delete($this->db->quoteName('#__fdshop_user_email_changes'))->where('token_hash='.$this->db->quote(hash('sha256',$token)));$this->db->setQuery($q)->execute();throw $e;}$this->history($userId,'email_change_requested','E-Mail-Änderung angefordert');
    }

    public function verifyEmail(string $token):void
    {
        if(!preg_match('/^[a-f0-9]{64}$/',$token))throw new \DomainException('Der Bestätigungslink ist ungültig.');$hash=hash('sha256',$token);$q=$this->db->getQuery(true)->select('*')->from($this->db->quoteName('#__fdshop_user_email_changes'))->where('token_hash='.$this->db->quote($hash))->where('consumed_at IS NULL')->where('expires_at>'.$this->db->quote(Factory::getDate()->toSql()));$this->db->setQuery($q);$pending=$this->db->loadObject();if(!$pending)throw new \DomainException('Der Bestätigungslink ist ungültig, abgelaufen oder wurde bereits verwendet.');$user=$this->user((int)$pending->user_id);$user->email=(string)$pending->new_email;if(!$user->save())throw new \RuntimeException($user->getError()?:'E-Mail-Adresse konnte nicht geändert werden.');$date=Factory::getDate()->toSql();$q=$this->db->getQuery(true)->update($this->db->quoteName('#__fdshop_user_email_changes'))->set('consumed_at='.$this->db->quote($date))->where('id='.(int)$pending->id)->where('consumed_at IS NULL');$this->db->setQuery($q)->execute();$this->history((int)$pending->user_id,'email_change_confirmed','E-Mail-Änderung bestätigt');
    }

    public function requestShipment(int $userId,int $orderId,int $shipmentId):void
    {
        $order=$this->ownedOrder($userId,$orderId);if($shipmentId===(int)$order->shipment_id)throw new \DomainException('Die gewünschte Abholstation entspricht der aktuellen Station.');$q=$this->db->getQuery(true)->select('*')->from($this->db->quoteName('#__fdshop_shipments'))->where('id='.(int)$shipmentId)->where('published=1');$this->db->setQuery($q);$shipment=$this->db->loadObject();if(!$shipment)throw new \DomainException('Die gewünschte Abholstation ist nicht verfügbar.');$q=$this->db->getQuery(true)->select('COUNT(*)')->from($this->db->quoteName('#__fdshop_order_shipment_requests'))->where('order_id='.(int)$orderId)->where("status='open'");$this->db->setQuery($q);if((int)$this->db->loadResult()>0)throw new \DomainException('Für diese Bestellung liegt bereits eine Änderungsanfrage zur Abholstation vor.');$row=(object)['order_id'=>$orderId,'user_id'=>$userId,'current_shipment_id'=>(int)$order->shipment_id,'requested_shipment_id'=>$shipmentId,'status'=>'open','created'=>Factory::getDate()->toSql()];$this->db->insertObject('#__fdshop_order_shipment_requests',$row);$id=(int)$this->db->insertid();try{$this->mail($this->companyEmail(),'FDShop Abholstationsanfrage '.$order->order_number,'Bestellung: '.htmlspecialchars($order->order_number).'<br>Aktuell: '.htmlspecialchars($order->shipment_name).'<br>Gewünscht: '.htmlspecialchars($shipment->shipment_name));}catch(\Throwable $e){$q=$this->db->getQuery(true)->delete($this->db->quoteName('#__fdshop_order_shipment_requests'))->where('id='.$id);$this->db->setQuery($q)->execute();throw $e;}$this->orderHistory($orderId,'shipment_request','Abholstationsanfrage gestellt',(string)$shipment->shipment_name,$id);$this->history($userId,'shipment_request','Abholstationsanfrage gestellt','order',$orderId);
    }

    public function declareWithdrawal(int $userId,int $orderId):void
    {
        $order=$this->ownedOrder($userId,$orderId);if((string)$order->withdrawal_status!=='none')throw new \DomainException('Für diese Bestellung wurde bereits ein Widerruf bearbeitet oder erklärt.');$date=Factory::getDate()->toSql();$q=$this->db->getQuery(true)->update($this->db->quoteName('#__fdshop_orders'))->set("withdrawal_status='declared'")->set('withdrawal_declared_at='.$this->db->quote($date))->where('id='.(int)$orderId)->where("withdrawal_status='none'");$this->db->setQuery($q)->execute();if($this->db->getAffectedRows()!==1)throw new \DomainException('Der Widerruf wurde bereits verarbeitet.');$this->orderHistory($orderId,'withdrawal_declared','Widerruf erklärt');$this->history($userId,'withdrawal_declared','Widerruf erklärt','order',$orderId);try{$this->mail((string)$order->customer_email,'Empfang Ihres Widerrufs '.$order->order_number,'Wir bestätigen den Eingang Ihrer Widerrufserklärung. Sie wird nun geprüft.');$this->mail($this->companyEmail(),'FDShop Widerruf erklärt '.$order->order_number,'Der Kunde hat den Widerruf für Bestellung '.htmlspecialchars($order->order_number).' erklärt.');}catch(\Throwable $e){throw new \RuntimeException('Ihr Widerruf wurde sicher erfasst, die E-Mail-Bestätigung konnte jedoch nicht vollständig versendet werden. Bitte kontaktieren Sie uns bei Bedarf.',0,$e);}
    }

    public function submitF3Documents(int $userId,array $files):void
    {
        $config=$this->config();$max=max(1,(int)($config->account_f3_max_mb??8))*1024*1024;$allowed=['application/pdf'=>'pdf','image/jpeg'=>'jpg','image/png'=>'png'];$attachments=[];$names=[];
        try{foreach(['permit'=>'Schein','identity'=>'Ausweis'] as $slot=>$label){$f=$files[$slot]??null;if(!$f||($f['error']??UPLOAD_ERR_NO_FILE)===UPLOAD_ERR_NO_FILE)continue;if((int)$f['error']!==UPLOAD_ERR_OK||!is_uploaded_file((string)$f['tmp_name']))throw new \DomainException('Der Dokumentupload ist fehlgeschlagen.');if((int)$f['size']>$max)throw new \DomainException('Eine Datei überschreitet die erlaubte Größe.');$mime=(new \finfo(FILEINFO_MIME_TYPE))->file((string)$f['tmp_name']);if(!isset($allowed[$mime]))throw new \DomainException('Erlaubt sind ausschließlich PDF-, JPG- und PNG-Dateien.');$target=sys_get_temp_dir().DIRECTORY_SEPARATOR.'fdshop-'.bin2hex(random_bytes(18)).'.'.$allowed[$mime];if(!move_uploaded_file((string)$f['tmp_name'],$target))throw new \RuntimeException('Die temporäre Datei konnte nicht sicher übernommen werden.');chmod($target,0600);$attachments[]=$target;$names[]=$label.'.'.$allowed[$mime];}if($attachments===[])throw new \DomainException('Bitte laden Sie mindestens einen Nachweis hoch.');$mailer=Factory::getMailer();$mailer->addRecipient($this->companyEmail());$mailer->setSubject('FDShop F3-Unterlagen Kundenkonto '.$userId);$mailer->isHtml(true);$mailer->setBody('Ein angemeldeter Kunde hat Unterlagen zur manuellen F3-Prüfung eingereicht. Keine automatische Freischaltung wurde vorgenommen.');foreach($attachments as $i=>$path)$mailer->addAttachment($path,$names[$i]);if($mailer->send()!==true)throw new \RuntimeException('Die Unterlagen konnten nicht per E-Mail übermittelt werden.');$this->history($userId,'f3_documents_submitted','F3-Unterlagen zur Prüfung eingereicht');}finally{foreach($attachments as $path)if(is_file($path))unlink($path);}
    }

    public function decideWithdrawal(int $orderId,bool $accept,string $reason,int $adminId):void
    {
        $q=$this->db->getQuery(true)->select('*')->from($this->db->quoteName('#__fdshop_orders'))->where('id='.(int)$orderId);$this->db->setQuery($q);$order=$this->db->loadObject();if(!$order||(string)$order->withdrawal_status!=='declared')throw new \DomainException('Der Widerruf ist nicht mehr offen.');if(!$accept&&trim($reason)==='')throw new \DomainException('Bitte geben Sie eine individuelle Ablehnungsbegründung an.');$date=Factory::getDate()->toSql();if($accept){$q=$this->db->getQuery(true)->select('id')->from($this->db->quoteName('#__fdshop_order_statuses'))->where("status_code='cancelled'")->where('is_active=1');$this->db->setQuery($q);$statusId=(int)$this->db->loadResult();if(!$statusId)throw new \RuntimeException('Der zentrale Bestellstatus Storniert ist nicht aktiv.');$this->orders->changeStatus($orderId,$statusId,'Widerruf akzeptiert');}$state=$accept?'accepted':'rejected';$q=$this->db->getQuery(true)->update($this->db->quoteName('#__fdshop_orders'))->set('withdrawal_status='.$this->db->quote($state))->set('withdrawal_decided_at='.$this->db->quote($date))->set('withdrawal_decided_by='.(int)$adminId)->set('withdrawal_decision_text='.$this->db->quote(trim($reason)))->where('id='.(int)$orderId)->where("withdrawal_status='declared'");$this->db->setQuery($q)->execute();$subject=$accept?'Widerruf akzeptiert ':'Widerruf abgelehnt ';$body=$accept?'Ihr Widerruf wurde akzeptiert.':'Ihr Widerruf wurde abgelehnt.<br>Begründung: '.htmlspecialchars(trim($reason));$this->mail((string)$order->customer_email,$subject.$order->order_number,$body);$this->orderHistory($orderId,'withdrawal_'.$state,$accept?'Widerruf akzeptiert':'Widerruf abgelehnt',$reason);
    }

    public function resolveShipmentRequest(int $orderId,int $adminId):void{$date=Factory::getDate()->toSql();$q=$this->db->getQuery(true)->update($this->db->quoteName('#__fdshop_order_shipment_requests'))->set("status='resolved'")->set('resolved_at='.$this->db->quote($date))->set('resolved_by='.(int)$adminId)->where('order_id='.(int)$orderId)->where("status='open'");$this->db->setQuery($q)->execute();if($this->db->getAffectedRows()<1)throw new \DomainException('Es liegt keine offene Abholstationsanfrage vor.');$this->orderHistory($orderId,'shipment_request_resolved','Abholstationsanfrage erledigt');}

    private function user(int $id){if($id<1)throw new \DomainException('Bitte melden Sie sich an.');$user=Factory::getContainer()->get(UserFactoryInterface::class)->loadUserById($id);if(!$user||$user->guest)throw new \DomainException('Das Benutzerkonto wurde nicht gefunden.');return $user;}
    private function ownedOrder(int $userId,int $orderId):object{$q=$this->db->getQuery(true)->select(['o.*','s.status_name','sr.id AS open_shipment_request_id'])->from($this->db->quoteName('#__fdshop_orders','o'))->leftJoin($this->db->quoteName('#__fdshop_order_statuses','s').' ON s.id=o.order_status_id')->leftJoin($this->db->quoteName('#__fdshop_order_shipment_requests','sr')." ON sr.order_id=o.id AND sr.status='open'")->where('o.id='.(int)$orderId)->where('o.user_id='.(int)$userId);$this->db->setQuery($q);$row=$this->db->loadObject();if(!$row)throw new \DomainException('Die Bestellung wurde nicht gefunden.',404);return $row;}
    private function profile(int $id):array{$out=array_fill_keys(['first_name','last_name','company','street','postal_code','city','country','phone'],'');$q=$this->db->getQuery(true)->select(['profile_key','profile_value'])->from($this->db->quoteName('#__user_profiles'))->where('user_id='.(int)$id)->where("profile_key LIKE 'fdshop_customer.%'");$this->db->setQuery($q);foreach((array)$this->db->loadRowList() as [$k,$v]){$f=substr($k,16);if(array_key_exists($f,$out))$out[$f]=(string)(json_decode($v,true)??$v);}return $out;}
    private function profileConfiguration():array{$defaults=['first_name'=>2,'last_name'=>2,'company'=>1,'street'=>2,'postal_code'=>2,'city'=>2,'country'=>2,'phone'=>1];$plugin=PluginHelper::getPlugin('user','fdshopprofile');$params=new Registry($plugin->params??'');$active=[];$required=[];foreach($defaults as $field=>$default){$status=in_array($field,['first_name','last_name'],true)?2:(int)$params->get('field_'.$field,$default);$active[$field]=$status>0;if($status===2)$required[]=$field;}return ['active'=>$active,'required'=>$required];}
    private function assertPasswordPolicy(string $password):void{$params=ComponentHelper::getParams('com_users');$rules=['minimum_length'=>[mb_strlen($password),'Zeichen'],'minimum_integers'=>[preg_match_all('/[0-9]/u',$password),'Ziffern'],'minimum_symbols'=>[preg_match_all('/[^\pL\pN]/u',$password),'Sonderzeichen'],'minimum_uppercase'=>[preg_match_all('/\p{Lu}/u',$password),'Großbuchstaben'],'minimum_lowercase'=>[preg_match_all('/\p{Ll}/u',$password),'Kleinbuchstaben']];foreach($rules as $key=>[$actual,$label]){$required=(int)$params->get($key,$key==='minimum_length'?12:0);if($actual<$required)throw new \DomainException('Das neue Passwort muss mindestens '.$required.' '.$label.' enthalten.');}}
    private function config():object{$q=$this->db->getQuery(true)->select('*')->from($this->db->quoteName('#__fdshop_config'))->where('id=1');$this->db->setQuery($q);return $this->db->loadObject()?:new \stdClass();}
    private function companyEmail():string{$email=(string)($this->config()->document_company_email??'');return filter_var($email,FILTER_VALIDATE_EMAIL)?$email:(string)Factory::getApplication()->get('mailfrom');}
    private function mail(string $to,string $subject,string $body):void{$mailer=Factory::getMailer();$mailer->addRecipient($to);$mailer->setSubject($subject);$mailer->isHtml(true);$mailer->setBody($body);if($mailer->send()!==true)throw new \RuntimeException('Die E-Mail konnte nicht versendet werden.');}
    private function history(int $userId,string $type,string $title,?string $referenceType=null,?int $referenceId=null):void{$row=(object)['user_id'=>$userId,'event_type'=>$type,'event_title'=>$title,'reference_type'=>$referenceType,'reference_id'=>$referenceId,'created'=>Factory::getDate()->toSql()];$this->db->insertObject('#__fdshop_user_history',$row);}
    private function orderHistory(int $orderId,string $type,string $title,?string $text=null,?int $referenceId=null):void{$this->orders->writeOrderHistory($orderId,$type,$title,$text,'account_request',$referenceId,true);}
}
