<?php
namespace FDShop\Component\FDShop\Site\Service;
defined('_JEXEC') or die;
use Joomla\CMS\Factory;
use Joomla\Database\DatabaseInterface;
use Joomla\Database\ParameterType;
final class ComparisonService
{
 private const KEY='fdshop.active_comparison';
 public function __construct(private readonly DatabaseInterface$db){}
 public function config():object{$this->db->setQuery('SELECT comparison_active,comparison_max_products,comparison_max_saved_lists FROM '.$this->db->quoteName('#__fdshop_config').' WHERE id=1');return$this->db->loadObject()?:(object)['comparison_active'=>1,'comparison_max_products'=>4,'comparison_max_saved_lists'=>4];}
 public function state():array{$cfg=$this->config();$raw=(array)Factory::getApplication()->getSession()->get(self::KEY,[]);$ids=array_values(array_unique(array_filter(array_map('intval',(array)($raw['product_ids']??[])))));return['enabled'=>(int)$cfg->comparison_active===1,'category_id'=>(int)($raw['category_id']??0),'product_ids'=>$ids,'count'=>count($ids),'max'=>(int)$cfg->comparison_max_products,'guest'=>(int)Factory::getApplication()->getIdentity()->id<1];}
 public function add(int$productId,int$categoryId,bool$replace=false):array{$state=$this->state();if(!$state['enabled'])throw new \DomainException('Der Produktvergleich ist derzeit deaktiviert.');$this->assertProduct($productId,$categoryId);if($state['product_ids']&&$state['category_id']!==$categoryId){if(!$replace)return$state+['requires_confirmation'=>true];$state['product_ids']=[];$state['category_id']=$categoryId;}if(!$state['product_ids'])$state['category_id']=$categoryId;if(!in_array($productId,$state['product_ids'],true)){if(count($state['product_ids'])>=$state['max'])throw new \DomainException('Es können maximal '.$state['max'].' Produkte verglichen werden.');$state['product_ids'][]=$productId;}$this->store($state);return$this->state()+['product_name'=>$this->productName($productId)];}
 public function remove(int$productId):array{$s=$this->state();$s['product_ids']=array_values(array_diff($s['product_ids'],[$productId]));if(!$s['product_ids'])$s['category_id']=0;$this->store($s);return$this->state();}
 public function clear():array{$this->store(['category_id'=>0,'product_ids'=>[]]);return$this->state();}
 public function products():array{$s=$this->state();if(!$s['product_ids'])return[];$now=Factory::getDate()->toSql();$q=$this->db->getQuery(true)->select(['p.id','p.product_name','p.alias','p.sale_price','p.discount_price','p.discount_active','p.currency','p.in_stock','p.nem','p.shot_count','p.caliber','p.burn_time','p.rise_height','m.manufacturer_name','MIN(media.path_small) AS image'])->from('#__fdshop_products AS p')->leftJoin('#__fdshop_manufacturers AS m ON m.id=p.manufacturer_id')->leftJoin("#__fdshop_media AS media ON media.product_id=p.id AND media.media_type='image'")->whereIn('p.id',$s['product_ids'])->where('p.is_active=1')->where('p.is_deleted=0')->where('(p.publish_up IS NULL OR p.publish_up<='.$this->db->quote($now).')')->where('(p.publish_down IS NULL OR p.publish_down>='.$this->db->quote($now).')')->group('p.id');$this->db->setQuery($q);$rows=[];foreach((array)$this->db->loadObjectList()as$r)$rows[(int)$r->id]=$r;$out=[];foreach($s['product_ids']as$id)if(isset($rows[$id]))$out[]=$rows[$id];return$out;}
 public function categories(array$productIds):array{$ids=array_values(array_unique(array_filter(array_map('intval',$productIds))));if(!$ids)return[];$q=$this->db->getQuery(true)->select(['product_id','MIN(category_id) AS category_id'])->from('#__fdshop_product_category_map')->whereIn('product_id',$ids)->group('product_id');$this->db->setQuery($q);$out=[];foreach((array)$this->db->loadObjectList()as$row)$out[(int)$row->product_id]=(int)$row->category_id;return$out;}
 public function saved(int$user):array{$this->assertUser($user);$q=$this->db->getQuery(true)->select(['l.id','l.name','l.category_id','l.modified','COUNT(i.product_id) AS product_count'])->from('#__fdshop_comparison_lists AS l')->leftJoin('#__fdshop_comparison_items AS i ON i.list_id=l.id')->where('l.user_id='.$user)->group('l.id')->order('l.modified DESC');$this->db->setQuery($q);return(array)$this->db->loadObjectList();}
 public function save(int$user,string$name):object{$this->assertUser($user);$s=$this->state();if(!$s['product_ids'])throw new \DomainException('Der aktive Vergleich ist leer.');$name=$this->name($name);$cfg=$this->config();$q=$this->db->getQuery(true)->select('COUNT(*)')->from('#__fdshop_comparison_lists')->where('user_id='.$user);$this->db->setQuery($q);if((int)$this->db->loadResult()>=(int)$cfg->comparison_max_saved_lists)throw new \DomainException('Die maximale Anzahl gespeicherter Vergleiche ist erreicht.');$now=Factory::getDate()->toSql();$row=(object)['user_id'=>$user,'category_id'=>$s['category_id'],'name'=>$name,'created'=>$now,'modified'=>$now];$this->db->transactionStart();try{$this->db->insertObject('#__fdshop_comparison_lists',$row);$id=(int)$this->db->insertid();foreach($s['product_ids']as$n=>$product){$item=(object)['list_id'=>$id,'product_id'=>$product,'ordering'=>$n];$this->db->insertObject('#__fdshop_comparison_items',$item);}$this->db->transactionCommit();}catch(\Throwable$e){$this->db->transactionRollback();throw$e;}return(object)['id'=>$id,'name'=>$name];}
 public function activate(int$user,int$id):array{$list=$this->owned($user,$id);$q=$this->db->getQuery(true)->select('product_id')->from('#__fdshop_comparison_items')->where('list_id='.$id)->order('ordering');$this->db->setQuery($q);$this->store(['category_id'=>(int)$list->category_id,'product_ids'=>array_map('intval',$this->db->loadColumn())]);return$this->state();}
 public function rename(int$user,int$id,string$name):void{$this->owned($user,$id);$q=$this->db->getQuery(true)->update('#__fdshop_comparison_lists')->set('name='.$this->db->quote($this->name($name)))->set('modified='.$this->db->quote(Factory::getDate()->toSql()))->where('id='.$id)->where('user_id='.$user);$this->db->setQuery($q)->execute();}
 public function delete(int$user,int$id):void{$this->owned($user,$id);$this->db->transactionStart();try{$this->db->setQuery($this->db->getQuery(true)->delete('#__fdshop_comparison_items')->where('list_id='.$id))->execute();$this->db->setQuery($this->db->getQuery(true)->delete('#__fdshop_comparison_lists')->where('id='.$id)->where('user_id='.$user))->execute();$this->db->transactionCommit();}catch(\Throwable$e){$this->db->transactionRollback();throw$e;}}
 private function assertProduct(int$product,int$category):void{if($category<1)throw new \DomainException('Für den Vergleich fehlt der eindeutige Kategoriekontext.');$now=Factory::getDate()->toSql();$q=$this->db->getQuery(true)->select('COUNT(*)')->from('#__fdshop_products AS p')->innerJoin('#__fdshop_product_category_map AS pcm ON pcm.product_id=p.id')->where('p.id='.$product)->where('pcm.category_id='.$category)->where('p.is_active=1')->where('p.is_deleted=0')->where('(p.publish_up IS NULL OR p.publish_up<='.$this->db->quote($now).')')->where('(p.publish_down IS NULL OR p.publish_down>='.$this->db->quote($now).')');$this->db->setQuery($q);if(!(int)$this->db->loadResult())throw new \DomainException('Das Produkt ist in dieser Kategorie nicht vergleichbar.');}
 private function owned(int$user,int$id):object{$this->assertUser($user);$q=$this->db->getQuery(true)->select('*')->from('#__fdshop_comparison_lists')->where('id='.$id)->where('user_id='.$user);$this->db->setQuery($q);$row=$this->db->loadObject();if(!$row)throw new \DomainException('Der gespeicherte Vergleich wurde nicht gefunden.');return$row;}
 private function productName(int$id):string{$this->db->setQuery('SELECT product_name FROM '.$this->db->quoteName('#__fdshop_products').' WHERE id='.$id);return(string)$this->db->loadResult();}
 private function name(string$n):string{$n=trim(preg_replace('/\s+/u',' ',$n));if($n===''||mb_strlen($n)>100)throw new \DomainException('Bitte gib einen Namen mit maximal 100 Zeichen ein.');return$n;}
 private function store(array$s):void{Factory::getApplication()->getSession()->set(self::KEY,['category_id'=>(int)($s['category_id']??0),'product_ids'=>array_values((array)($s['product_ids']??[]))]);}
 private function assertUser(int$id):void{if($id<1)throw new \DomainException('Bitte melde dich an.');}
}
