<?php
namespace FDShop\Component\FDShop\Site\Service;
defined('_JEXEC') or die;
use Joomla\CMS\Factory;
use Joomla\Database\DatabaseInterface;
use Joomla\Database\ParameterType;
final class FavoriteService
{
 public function __construct(private readonly DatabaseInterface $db){}
 public function config():object{$this->db->setQuery('SELECT favorites_active,favorites_max_custom_lists,favorites_max_products FROM '.$this->db->quoteName('#__fdshop_config').' WHERE id=1');return$this->db->loadObject()?: (object)['favorites_active'=>1,'favorites_max_custom_lists'=>3,'favorites_max_products'=>100];}
 public function enabled():bool{return(int)$this->config()->favorites_active===1;}
 public function defaultCount(int$userId):int{if($userId<1||!$this->enabled())return 0;$q=$this->db->getQuery(true)->select('COUNT(DISTINCT i.product_id)')->from('#__fdshop_favorite_items AS i')->innerJoin('#__fdshop_favorite_lists AS l ON l.id=i.list_id')->where('l.user_id='.$userId)->where('l.is_default=1');$this->db->setQuery($q);return(int)$this->db->loadResult();}
 public function ensureDefault(int$userId):object{$this->assertUser($userId);$q=$this->db->getQuery(true)->select('*')->from('#__fdshop_favorite_lists')->where('user_id='.$userId)->where('is_default=1');$this->db->setQuery($q);if($row=$this->db->loadObject())return$row;$now=Factory::getDate()->toSql();try{$record=(object)['user_id'=>$userId,'name'=>'Standardliste','is_default'=>1,'created'=>$now,'modified'=>$now];$this->db->insertObject('#__fdshop_favorite_lists',$record);}catch(\Throwable){$this->db->setQuery($q);if($row=$this->db->loadObject())return$row;throw new \RuntimeException('Die Standardliste konnte nicht angelegt werden.');}$this->db->setQuery($q);return$this->db->loadObject();}
 public function lists(int$userId,?int$productId=null):array{$this->ensureDefault($userId);$q=$this->db->getQuery(true)->select(['l.id','l.name','l.is_default','COUNT(i.product_id) AS product_count'])->from('#__fdshop_favorite_lists AS l')->leftJoin('#__fdshop_favorite_items AS i ON i.list_id=l.id')->where('l.user_id='.$userId)->group('l.id')->order('l.is_default DESC,l.created ASC');$this->db->setQuery($q);$rows=(array)$this->db->loadObjectList();if($productId){$q=$this->db->getQuery(true)->select('i.list_id')->from('#__fdshop_favorite_items AS i')->innerJoin('#__fdshop_favorite_lists AS l ON l.id=i.list_id')->where('l.user_id='.$userId)->where('i.product_id='.$productId);$this->db->setQuery($q);$selected=array_map('intval',$this->db->loadColumn());foreach($rows as$r)$r->selected=in_array((int)$r->id,$selected,true);}return$rows;}
 public function states(int$userId,array$productIds):array{if($userId<1||!$this->enabled())return[];$ids=array_values(array_unique(array_filter(array_map('intval',$productIds))));if(!$ids)return[];$q=$this->db->getQuery(true)->select(['i.product_id','COUNT(DISTINCT i.list_id) AS list_count'])->from('#__fdshop_favorite_items AS i')->innerJoin('#__fdshop_favorite_lists AS l ON l.id=i.list_id')->where('l.user_id='.$userId)->whereIn('i.product_id',$ids)->group('i.product_id');$this->db->setQuery($q);$out=[];foreach((array)$this->db->loadObjectList()as$r)$out[(int)$r->product_id]=(int)$r->list_count;return$out;}
 public function toggleDefault(int$userId,int$productId):array{$this->assertEnabled();$this->assertPublicProduct($productId);$list=$this->ensureDefault($userId);$q=$this->db->getQuery(true)->select('COUNT(*)')->from('#__fdshop_favorite_items')->where('list_id='.(int)$list->id)->where('product_id='.$productId);$this->db->setQuery($q);if((int)$this->db->loadResult()){$q=$this->db->getQuery(true)->delete('#__fdshop_favorite_items')->where('list_id='.(int)$list->id)->where('product_id='.$productId);$this->db->setQuery($q)->execute();return['active'=>false,'list_count'=>0,'default_count'=>$this->defaultCount($userId)];}$this->add((int)$list->id,$userId,$productId);return['active'=>true,'list_count'=>1,'default_count'=>$this->defaultCount($userId)];}
 public function saveMemberships(int$userId,int$productId,array$listIds):array{$this->assertEnabled();$this->assertPublicProduct($productId);$owned=array_map(fn($r)=>(int)$r->id,$this->lists($userId));$wanted=array_values(array_unique(array_intersect($owned,array_map('intval',$listIds))));$this->db->transactionStart();try{$q=$this->db->getQuery(true)->delete('#__fdshop_favorite_items')->where('product_id='.$productId);if($owned)$q->whereIn('list_id',$owned);else$q->where('1=0');$this->db->setQuery($q)->execute();foreach($wanted as$id)$this->add($id,$userId,$productId);$this->db->transactionCommit();}catch(\Throwable$e){$this->db->transactionRollback();throw$e;}return['active'=>(bool)$wanted,'list_count'=>count($wanted),'default_count'=>$this->defaultCount($userId)];}
 public function createList(int$userId,string$name):object{$this->assertEnabled();$this->ensureDefault($userId);$name=$this->cleanName($name);$cfg=$this->config();$q=$this->db->getQuery(true)->select('COUNT(*)')->from('#__fdshop_favorite_lists')->where('user_id='.$userId)->where('is_default=0');$this->db->setQuery($q);if((int)$this->db->loadResult()>=(int)$cfg->favorites_max_custom_lists)throw new \DomainException('Die maximale Anzahl zusätzlicher Favoritenlisten ist erreicht.');$now=Factory::getDate()->toSql();$record=(object)['user_id'=>$userId,'name'=>$name,'is_default'=>0,'created'=>$now,'modified'=>$now];$this->db->insertObject('#__fdshop_favorite_lists',$record);return(object)['id'=>(int)$this->db->insertid(),'name'=>$name,'is_default'=>0];}
 public function renameList(int$userId,int$id,string$name):void{$list=$this->owned($userId,$id);if((int)$list->is_default===1)throw new \DomainException('Die Standardliste kann nicht umbenannt werden.');$name=$this->cleanName($name);$q=$this->db->getQuery(true)->update('#__fdshop_favorite_lists')->set('name='.$this->db->quote($name))->set('modified='.$this->db->quote(Factory::getDate()->toSql()))->where('id='.$id)->where('user_id='.$userId);$this->db->setQuery($q)->execute();}
 public function deleteList(int$userId,int$id):void{$list=$this->owned($userId,$id);if((int)$list->is_default===1)throw new \DomainException('Die Standardliste kann nicht gelöscht werden.');$this->db->transactionStart();try{$this->db->setQuery($this->db->getQuery(true)->delete('#__fdshop_favorite_items')->where('list_id='.$id))->execute();$this->db->setQuery($this->db->getQuery(true)->delete('#__fdshop_favorite_lists')->where('id='.$id)->where('user_id='.$userId))->execute();$this->db->transactionCommit();}catch(\Throwable$e){$this->db->transactionRollback();throw$e;}}
 private function add(int$listId,int$userId,int$productId):void{$this->owned($userId,$listId);$cfg=$this->config();$q=$this->db->getQuery(true)->select('COUNT(*)')->from('#__fdshop_favorite_items')->where('list_id='.$listId);$this->db->setQuery($q);if((int)$this->db->loadResult()>=(int)$cfg->favorites_max_products)throw new \DomainException('Diese Favoritenliste hat ihr Produktlimit erreicht.');try{$record=(object)['list_id'=>$listId,'product_id'=>$productId,'created'=>Factory::getDate()->toSql()];$this->db->insertObject('#__fdshop_favorite_items',$record);}catch(\Throwable$e){if(!str_contains(strtolower($e->getMessage()),'duplicate'))throw$e;}}
 private function owned(int$userId,int$id):object{$this->assertUser($userId);$q=$this->db->getQuery(true)->select('*')->from('#__fdshop_favorite_lists')->where('id='.$id)->where('user_id='.$userId);$this->db->setQuery($q);$row=$this->db->loadObject();if(!$row)throw new \DomainException('Die Favoritenliste wurde nicht gefunden.');return$row;}
 private function assertPublicProduct(int$id):void{$now=Factory::getDate()->toSql();$q=$this->db->getQuery(true)->select('COUNT(*)')->from('#__fdshop_products')->where('id='.$id)->where('is_active=1')->where('is_deleted=0')->where('(publish_up IS NULL OR publish_up<='.$this->db->quote($now).')')->where('(publish_down IS NULL OR publish_down>='.$this->db->quote($now).')');$this->db->setQuery($q);if(!(int)$this->db->loadResult())throw new \DomainException('Das Produkt ist nicht verfügbar.');}
 private function cleanName(string$name):string{$name=trim(preg_replace('/\s+/u',' ',$name));if(mb_strlen($name)<1||mb_strlen($name)>100)throw new \DomainException('Bitte gib einen Listennamen mit maximal 100 Zeichen ein.');return$name;}
 private function assertEnabled():void{if(!$this->enabled())throw new \DomainException('Favoriten sind derzeit deaktiviert.');}
 private function assertUser(int$id):void{if($id<1)throw new \DomainException('Bitte melde dich an.');}
}
