<?php
namespace FDShop\Component\FDShop\Site\Model;
defined('_JEXEC') or die;
use FDShop\Component\FDShop\Site\Helper\FavoriteHelper;
use FDShop\Component\FDShop\Site\Helper\ProductCardHelper;
use Joomla\CMS\Factory;
use Joomla\CMS\MVC\Model\BaseDatabaseModel;
use Joomla\Database\ParameterType;
final class FavoritesModel extends BaseDatabaseModel
{
 public function getData():array{$user=(int)Factory::getApplication()->getIdentity()->id;if($user<1)return['lists'=>[],'selected'=>0,'items'=>[]];$service=FavoriteHelper::service();$lists=$service->lists($user);$selected=Factory::getApplication()->getInput()->getInt('list_id',(int)($lists[0]->id??0));if(!in_array($selected,array_map(fn($l)=>(int)$l->id,$lists),true))$selected=(int)($lists[0]->id??0);$items=$this->products($user,$selected);return compact('lists','selected','items');}
 private function products(int$user,int$list):array{$db=$this->getDatabase();$now=Factory::getDate()->toSql();$price='CASE WHEN p.discount_active=1 AND p.discount_price>0 THEN p.discount_price ELSE p.sale_price END';$q=$db->getQuery(true)->select(['p.id','p.product_name','p.alias','pd.sku','p.short_description','p.sale_price','p.discount_price','p.discount_active','p.currency','p.in_stock','p.unit_type','p.min_order_qty','p.max_order_qty','p.step_order_qty','p.nem','p.shot_count','p.caliber','p.burn_time','p.rise_height','p.ribbon_new','p.ribbon_hot','p.ribbon_bundle','m.manufacturer_name','bg.alias AS buyer_group_alias',$price.' AS current_price','MIN(pcm.category_id) AS category_id'])->from('#__fdshop_favorite_items AS fi')->innerJoin('#__fdshop_favorite_lists AS fl ON fl.id=fi.list_id')->innerJoin('#__fdshop_products AS p ON p.id=fi.product_id')->leftJoin('#__fdshop_products_details AS pd ON pd.product_id=p.id')->leftJoin('#__fdshop_manufacturers AS m ON m.id=p.manufacturer_id')->leftJoin('#__fdshop_buyer_groups AS bg ON bg.id=p.buyer_group_id')->leftJoin('#__fdshop_product_category_map AS pcm ON pcm.product_id=p.id')->where('fl.id='.$list)->where('fl.user_id='.$user)->where('p.is_active=1')->where('p.is_deleted=0')->where('(p.publish_up IS NULL OR p.publish_up<='.$db->quote($now).')')->where('(p.publish_down IS NULL OR p.publish_down>='.$db->quote($now).')')->group('p.id')->order('fi.created DESC');$db->setQuery($q);$items=(array)$db->loadObjectList();$media=$this->media(array_map(fn($i)=>(int)$i->id,$items));foreach($items as$i){$i->media=$media[(int)$i->id]??['standard'=>null,'small'=>null,'mobile'=>null,'video'=>null];ProductCardHelper::prepare($i,(int)$i->category_id);}return$items;}
 private function media(array$ids):array{if(!$ids)return[];$db=$this->getDatabase();$q=$db->getQuery(true)->select(['product_id','media_type','external_url','path_standard','path_small','path_mobile'])->from('#__fdshop_media')->whereIn('product_id',$ids)->whereIn('media_type',['image','youtube'],ParameterType::STRING)->order('product_id,is_primary DESC,ordering,id');$db->setQuery($q);$out=[];foreach((array)$db->loadObjectList()as$m){$id=(int)$m->product_id;$out[$id]??=['standard'=>null,'small'=>null,'mobile'=>null,'video'=>null];if($m->media_type==='image'&&!$out[$id]['standard']){$out[$id]['standard']=$m->path_standard?:$m->path_small?:$m->path_mobile;$out[$id]['small']=$m->path_small?:$m->path_standard?:$m->path_mobile;$out[$id]['mobile']=$m->path_mobile?:$m->path_small?:$m->path_standard;}elseif($m->media_type==='youtube'&&!$out[$id]['video'])$out[$id]['video']=$this->video((string)$m->external_url);}return$out;}
 private function video(string$url):?string{$p=parse_url(trim($url));$host=strtolower((string)($p['host']??''));$id='';if(str_contains($host,'youtu.be'))$id=trim((string)($p['path']??''),'/');elseif(str_contains($host,'youtube')){parse_str((string)($p['query']??''),$v);$id=(string)($v['v']??'');if(preg_match('~/(?:embed|shorts)/([A-Za-z0-9_-]{6,})~',(string)($p['path']??''),$m))$id=$m[1];}return preg_match('/^[A-Za-z0-9_-]{6,}$/',$id)?'https://www.youtube-nocookie.com/embed/'.$id:null;}
}
