<?php
namespace FDShop\Component\FDShop\Site\Model;
defined('_JEXEC') or die;
use FDShop\Component\FDShop\Site\Helper\ProductCardHelper;
use Joomla\CMS\Factory;
use Joomla\CMS\MVC\Model\ListModel;
use Joomla\Database\DatabaseQuery;
use Joomla\Database\ParameterType;
final class SearchModel extends ListModel
{
 protected function populateState($ordering='p.product_name',$direction='ASC'):void{$i=Factory::getApplication()->getInput();$limit=$i->getInt('limit',24);$limit=in_array($limit,[12,24,36,48],true)?$limit:24;$db=$this->getDatabase();$db->setQuery('SELECT search_active,search_suggestion_limit FROM '.$db->quoteName('#__fdshop_config').' WHERE id=1');$config=$db->loadObject();$this->setState('search.active',(int)($config->search_active??1));$this->setState('search.suggestion_limit',max(6,min(8,(int)($config->search_suggestion_limit??8))));$this->setState('search.query',trim((string)preg_replace('/\s+/u',' ',$i->getString('q',''))));$this->setState('list.limit',$limit);$this->setState('list.start',max(0,$i->getInt('limitstart',0)));}
 protected function getListQuery():DatabaseQuery{$db=$this->getDatabase();$now=Factory::getDate()->toSql();$price='CASE WHEN p.discount_active=1 AND p.discount_price>0 THEN p.discount_price ELSE p.sale_price END';$q=$db->getQuery(true)->select(['p.id','p.product_name','p.alias','pd.sku AS sku','p.short_description','p.sale_price','p.discount_price','p.discount_active','p.currency','p.in_stock','p.unit_type','p.min_order_qty','p.max_order_qty','p.step_order_qty','p.nem','p.shot_count','p.caliber','p.burn_time','p.rise_height','p.ribbon_new','p.ribbon_hot','p.ribbon_bundle','m.manufacturer_name','bg.alias AS buyer_group_alias',$price.' AS current_price','MIN(pcm.category_id) AS category_id'])->from('#__fdshop_products AS p')->leftJoin('#__fdshop_products_details AS pd ON pd.product_id=p.id')->leftJoin('#__fdshop_manufacturers AS m ON m.id=p.manufacturer_id')->leftJoin('#__fdshop_buyer_groups AS bg ON bg.id=p.buyer_group_id')->leftJoin('#__fdshop_product_category_map AS pcm ON pcm.product_id=p.id')->where('p.is_active=1')->where('p.is_deleted=0')->where('(p.publish_up IS NULL OR p.publish_up<=:up)')->where('(p.publish_down IS NULL OR p.publish_down>=:down)')->bind(':up',$now)->bind(':down',$now)->group('p.id');$tokens=array_slice(preg_split('/\s+/u',(string)$this->getState('search.query',''),-1,PREG_SPLIT_NO_EMPTY)?:[],0,5);foreach($tokens as $n=>$token){$name=':q'.$n.'n';$sku=':q'.$n.'s';$maker=':q'.$n.'m';$value='%'.$token.'%';$q->where('(p.product_name LIKE '.$name.' OR pd.sku LIKE '.$sku.' OR m.manufacturer_name LIKE '.$maker.')')->bind($name,$value,ParameterType::STRING)->bind($sku,$value,ParameterType::STRING)->bind($maker,$value,ParameterType::STRING);}if(!$tokens||(int)$this->getState('search.active',1)!==1)$q->where('1=0');return$q->order('p.product_name ASC,p.id ASC');}
 public function getItems():array{$items=parent::getItems();if(!$items)return[];$media=$this->media(array_map(static fn($i)=>(int)$i->id,$items));foreach($items as $item){$item->media=$media[(int)$item->id]??['standard'=>null,'small'=>null,'mobile'=>null,'video'=>null];ProductCardHelper::prepare($item,(int)$item->category_id);}return$items;}
 public function getSuggestions(int $limit=8):array{if((int)$this->getState('search.active',1)!==1||mb_strlen((string)$this->getState('search.query',''))<3)return[];$this->setState('list.limit',min((int)$this->getState('search.suggestion_limit',8),max(1,min(8,$limit))));$this->setState('list.start',0);return array_map(static fn($i)=>['name'=>$i->product_name,'sku'=>$i->sku,'manufacturer'=>$i->manufacturer_name,'price'=>$i->price_formatted,'image'=>$i->image_small_url?:$i->image_url,'url'=>$i->detail_url],$this->getItems());}
 private function media(array $ids):array{$ids=array_values(array_unique(array_filter(array_map('intval',$ids))));if(!$ids)return[];$db=$this->getDatabase();$q=$db->getQuery(true)->select(['product_id','media_type','external_url','path_standard','path_small','path_mobile'])->from('#__fdshop_media')->whereIn('product_id',$ids)->whereIn('media_type',['image','youtube'],ParameterType::STRING)->order('product_id ASC,is_primary DESC,ordering ASC,id ASC');$db->setQuery($q);$out=[];foreach($db->loadObjectList() as $m){$id=(int)$m->product_id;$out[$id]??=['standard'=>null,'small'=>null,'mobile'=>null,'video'=>null];if($m->media_type==='image'&&!$out[$id]['standard']){$out[$id]['standard']=$m->path_standard?:$m->path_small?:$m->path_mobile;$out[$id]['small']=$m->path_small?:$m->path_standard?:$m->path_mobile;$out[$id]['mobile']=$m->path_mobile?:$m->path_small?:$m->path_standard;}elseif($m->media_type==='youtube'&&!$out[$id]['video'])$out[$id]['video']=$this->video((string)$m->external_url);}return$out;}
 private function video(string $url):?string{$p=parse_url(trim($url));$host=strtolower((string)($p['host']??''));$id='';if(str_contains($host,'youtu.be'))$id=trim((string)($p['path']??''),'/');elseif(str_contains($host,'youtube')){parse_str((string)($p['query']??''),$v);$id=(string)($v['v']??'');if(preg_match('~/(?:embed|shorts)/([A-Za-z0-9_-]{6,})~',(string)($p['path']??''),$m))$id=$m[1];}return preg_match('/^[A-Za-z0-9_-]{6,}$/',$id)?'https://www.youtube-nocookie.com/embed/'.$id:null;}
}
