(function(){
  'use strict';
  var dialog=null;
  function post(url,data,token){var body=new URLSearchParams(data);body.set(token,'1');return fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Accept':'application/json'},body:body}).then(function(r){return r.json();}).then(function(r){if(r.success===false)throw new Error(r.message||'Aktion fehlgeschlagen.');return r.data||r;});}
  function update(id,state){document.querySelectorAll('[data-fdshop-favorite][data-favorite-product-id="'+id+'"]').forEach(function(b){b.classList.toggle('is-active',state);b.setAttribute('aria-pressed',state?'true':'false');var label=b.getAttribute('aria-label').split(': ').slice(1).join(': ');b.setAttribute('aria-label',(state?'Aus Favoriten entfernen':'Zu Favoriten hinzufügen')+': '+label);});}
  function modal(){if(dialog)return dialog;dialog=document.createElement('dialog');dialog.className='fdshop-favorite-dialog';document.body.append(dialog);dialog.addEventListener('click',function(e){if(e.target===dialog||e.target.closest('[data-favorite-close]'))dialog.close();});return dialog;}
  function guest(){var d=modal(),ret=btoa(location.pathname+location.search);d.innerHTML='<form method="dialog"><button type="button" class="fdshop-favorite-dialog__close" data-favorite-close aria-label="Schließen">×</button><h2>Favoriten speichern</h2><p>Favoriten sind für registrierte Kunden verfügbar. Melde dich an oder erstelle kostenlos ein Kundenkonto, um Produkte dauerhaft in Favoritenlisten zu speichern.</p><div><a class="btn btn-primary" href="index.php?option=com_users&view=login&return='+encodeURIComponent(ret)+'">Anmelden</a> <a class="btn btn-outline-primary" href="index.php?option=com_users&view=registration&return='+encodeURIComponent(ret)+'">Registrieren</a> <button class="btn btn-secondary" type="button" data-favorite-close>Abbrechen</button></div></form>';d.showModal();}
  function choose(button,lists){var d=modal();d.innerHTML='<form><button type="button" class="fdshop-favorite-dialog__close" data-favorite-close aria-label="Schließen">×</button><h2>Favoritenlisten</h2><div data-favorite-options></div><button class="btn btn-primary" type="submit">Auswahl speichern</button> <button class="btn btn-secondary" type="button" data-favorite-close>Abbrechen</button></form>';var box=d.querySelector('[data-favorite-options]');lists.forEach(function(l){var label=document.createElement('label');label.innerHTML='<input type="checkbox" name="list_ids[]" value="'+l.id+'"> <span></span> <small></small>';label.querySelector('input').checked=!!l.selected;label.querySelector('span').textContent=l.name;label.querySelector('small').textContent=' ('+l.product_count+')';box.append(label);});d.querySelector('form').addEventListener('submit',function(e){e.preventDefault();var ids=Array.from(d.querySelectorAll('input:checked')).map(function(i){return i.value;});var data={product_id:button.dataset.favoriteProductId};ids.forEach(function(id,n){data['list_ids['+n+']']=id;});post(button.dataset.saveUrl,data,button.dataset.token).then(function(r){update(button.dataset.favoriteProductId,r.active);d.close();}).catch(function(e){alert(e.message);});});d.showModal();}
  document.addEventListener('click',function(e){var b=e.target.closest('[data-fdshop-favorite]');if(!b)return;e.preventDefault();if(b.dataset.guest==='1'){guest();return;}fetch(b.dataset.listsUrl+'&product_id='+encodeURIComponent(b.dataset.favoriteProductId),{headers:{Accept:'application/json'}}).then(function(r){return r.json();}).then(function(r){if(r.success===false)throw new Error(r.message);var lists=(r.data||r).lists||[];if(lists.length===1)return post(b.dataset.toggleUrl,{product_id:b.dataset.favoriteProductId},b.dataset.token).then(function(x){update(b.dataset.favoriteProductId,x.active);});choose(b,lists);}).catch(function(x){alert(x.message);});});
}());
