<?php
declare(strict_types=1);
define('_JEXEC',1);define('JPATH_BASE','/var/www/html');require JPATH_BASE.'/includes/defines.php';require JPATH_BASE.'/includes/framework.php';
require_once JPATH_ADMINISTRATOR.'/components/com_fdshop/src/Extension/FdshopComponent.php';require_once JPATH_ADMINISTRATOR.'/components/com_fdshop/src/Service/OrderDocumentService.php';require_once JPATH_ADMINISTRATOR.'/components/com_fdshop/src/Service/InvoiceService.php';
use FDShop\Component\FDShop\Administrator\Service\InvoiceService;use Joomla\CMS\Application\SiteApplication;use Joomla\CMS\Factory;use Joomla\Database\DatabaseInterface;use Joomla\Session\SessionInterface;
$_SERVER['HTTP_HOST']='localhost';$_SERVER['REQUEST_URI']='/';$_SERVER['SCRIPT_NAME']='/index.php';$c=Factory::getContainer();$c->alias(SessionInterface::class,'session.web.site');$app=$c->get(SiteApplication::class);Factory::$application=$app;$db=$c->get(DatabaseInterface::class);$svc=$app->bootComponent('com_fdshop')->getContainer()->get(InvoiceService::class);
$db->setQuery($db->getQuery(true)->select('*')->from($db->quoteName('#__fdshop_orders'))->where('id=900800'));$source=$db->loadObject();if(!$source)throw new RuntimeException('fixture order missing');
$db->setQuery($db->getQuery(true)->select('id')->from($db->quoteName('#__fdshop_order_statuses'))->where('create_invoice=1'),0,1);$paid=(int)$db->loadResult();if($paid<1)throw new RuntimeException('paid status missing');
$db->setQuery($db->getQuery(true)->select('id')->from($db->quoteName('#__fdshop_order_statuses'))->where('create_invoice=0'),0,1);$unpaidStatus=(int)$db->loadResult();if($unpaidStatus<1)throw new RuntimeException('unpaid status missing');
$ids=[];$files=[];$period=Factory::getDate('now','UTC')->format('ym',false);$db->setQuery($db->getQuery(true)->select('last_number')->from($db->quoteName('#__fdshop_invoice_sequences'))->where('period='.$db->quote($period)));$oldSequence=$db->loadResult();
$make=function(string $suffix,int $status)use($db,$source,&$ids):int{$o=clone $source;unset($o->id);$o->order_number='INV-TEST-'.$suffix.'-'.bin2hex(random_bytes(3));$o->submission_id=null;$o->invoice_number=null;$o->invoice_created_at=null;$o->invoice_cancelled_at=null;$o->order_status_id=$status;$o->order_status=$status?'paid':'pending';$db->insertObject('#__fdshop_orders',$o);$id=(int)$db->insertid();$ids[]=$id;$db->setQuery($db->getQuery(true)->select('*')->from($db->quoteName('#__fdshop_order_items'))->where('order_id=900800'));foreach((array)$db->loadObjectList() as $item){unset($item->id);$item->order_id=$id;$db->insertObject('#__fdshop_order_items',$item);}return $id;};
try{
    $same=$make('SAME',$paid);$a=$make('A',$paid);$b=$make('B',$paid);$unpaid=$make('UNPAID',$unpaidStatus);
    $run=function(array $orders):void{$procs=[];foreach($orders as $id){$cmd='php '.escapeshellarg(__DIR__.'/invoice-worker.php').' '.(int)$id;$pipes=[];$p=proc_open($cmd,[1=>['pipe','w'],2=>['pipe','w']],$pipes);if(!is_resource($p))throw new RuntimeException('worker start failed');$procs[]=[$p,$pipes];}foreach($procs as [$p,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($p)!==0)throw new RuntimeException('worker failed '.$out.$err);}};
    $run([$same,$same]);$run([$a,$b]);
    $db->setQuery($db->getQuery(true)->select('invoice_number')->from($db->quoteName('#__fdshop_orders'))->whereIn('id',[$same,$a,$b])->order('id ASC'));$numbers=(array)$db->loadColumn();if(count(array_unique($numbers))!==3)throw new RuntimeException('parallel invoices are not unique');foreach($numbers as $number)if(!preg_match('/^RE-\d{8}$/',$number))throw new RuntimeException('invoice format invalid');
    $before=$numbers[0];$first=$svc->issue($same);$db->setQuery($db->getQuery(true)->select('invoice_number')->from($db->quoteName('#__fdshop_orders'))->where('id='.$same));if($db->loadResult()!==$before)throw new RuntimeException('retry changed invoice number');
    $cancel=$svc->cancel($same);if(!$cancel||$cancel['version']!==1||!str_contains($cancel['name'],'STORNIERT'))throw new RuntimeException('cancelled invoice missing');$db->setQuery($db->getQuery(true)->select('COUNT(*)')->from($db->quoteName('#__fdshop_order_documents'))->where('order_id='.$same)->where('document_type='.$db->quote('invoice')));if((int)$db->loadResult()!==2)throw new RuntimeException('original/cancelled history missing');
    try{$svc->issue($unpaid);throw new RuntimeException('unpaid invoice accepted');}catch(RuntimeException $e){if($e->getMessage()==='unpaid invoice accepted')throw $e;}
    $layout=file_get_contents(JPATH_ADMINISTRATOR.'/components/com_fdshop/layouts/orderdocuments/customer.php');foreach(['#e0a721','inkl. MwSt.','Gesamtbetrag (Netto)','STORNIERT'] as $needle)if(!str_contains($layout,$needle))throw new RuntimeException('layout marker missing '.$needle);if(str_contains($layout,'table-layout: fixed')&&!str_contains($layout,'Kein table-layout: fixed'))throw new RuntimeException('fixed table layout regression');
    echo 'invoice regression PASS parallel-same-order parallel-distinct retry snapshot cancel-history unpaid-guard layout' . "\n";
}finally{
    if($ids){$db->setQuery($db->getQuery(true)->select('filename')->from($db->quoteName('#__fdshop_order_documents'))->whereIn('order_id',$ids));foreach((array)$db->loadColumn() as $name){$path=JPATH_ROOT.'/media/com_fdshop-private/documents/'.basename((string)$name);if(is_file($path))unlink($path);}$db->setQuery($db->getQuery(true)->delete($db->quoteName('#__fdshop_order_documents'))->whereIn('order_id',$ids))->execute();$db->setQuery($db->getQuery(true)->delete($db->quoteName('#__fdshop_order_items'))->whereIn('order_id',$ids))->execute();$db->setQuery($db->getQuery(true)->delete($db->quoteName('#__fdshop_orders'))->whereIn('id',$ids))->execute();}
    if($oldSequence===null)$db->setQuery($db->getQuery(true)->delete($db->quoteName('#__fdshop_invoice_sequences'))->where('period='.$db->quote($period)))->execute();else $db->setQuery($db->getQuery(true)->update($db->quoteName('#__fdshop_invoice_sequences'))->set('last_number='.(int)$oldSequence)->where('period='.$db->quote($period)))->execute();
}
