SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `#__fdshop_coupon_usage`;
DROP TABLE IF EXISTS `#__fdshop_coupon_category_map`;
DROP TABLE IF EXISTS `#__fdshop_coupon_product_map`;
DROP TABLE IF EXISTS `#__fdshop_coupon_buyer_group_map`;
DROP TABLE IF EXISTS `#__fdshop_coupon_user_map`;
DROP TABLE IF EXISTS `#__fdshop_coupons`;
DROP TABLE IF EXISTS `#__fdshop_order_status_history`;
DROP TABLE IF EXISTS `#__fdshop_order_history`;
DROP TABLE IF EXISTS `#__fdshop_order_bundle_items`;
DROP TABLE IF EXISTS `#__fdshop_order_bundles`;
DROP TABLE IF EXISTS `#__fdshop_order_items`;
DROP TABLE IF EXISTS `#__fdshop_orders`;
DROP TABLE IF EXISTS `#__fdshop_order_statuses`;
DROP TABLE IF EXISTS `#__fdshop_cart`;
DROP TABLE IF EXISTS `#__fdshop_bundle_discount_rules`;
DROP TABLE IF EXISTS `#__fdshop_bundle_items`;
DROP TABLE IF EXISTS `#__fdshop_bundles`;
DROP TABLE IF EXISTS `#__fdshop_media`;
DROP TABLE IF EXISTS `#__fdshop_product_buyer_group_map`;
DROP TABLE IF EXISTS `#__fdshop_product_category_map`;
DROP TABLE IF EXISTS `#__fdshop_product_prices_research`;
DROP TABLE IF EXISTS `#__fdshop_product_prices`;
DROP TABLE IF EXISTS `#__fdshop_price_calc_rules`;
DROP TABLE IF EXISTS `#__fdshop_products_details`;
DROP TABLE IF EXISTS `#__fdshop_user_buyer_group_map`;
DROP TABLE IF EXISTS `#__fdshop_products`;
DROP TABLE IF EXISTS `#__fdshop_buyer_groups`;
DROP TABLE IF EXISTS `#__fdshop_manufacturers`;
DROP TABLE IF EXISTS `#__fdshop_categories`;
DROP TABLE IF EXISTS `#__fdshop_shipments`;
DROP TABLE IF EXISTS `#__fdshop_payment_methods`;
DROP TABLE IF EXISTS `#__fdshop_config`;

SET FOREIGN_KEY_CHECKS = 1;
