<?php
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Router\Route;use Joomla\CMS\Session\Session;
$a=$this->data['analysis'];$token=Session::getFormToken();
?>
<div id="fdshop-master-import" data-start="<?php echo Route::_('index.php?option=com_fdshop&task=masterimageimport.startBatch&format=json',false); ?>" data-process="<?php echo Route::_('index.php?option=com_fdshop&task=masterimageimport.processBatch&format=json',false); ?>" data-token="<?php echo $token; ?>">
<div class="alert alert-info"><strong>Stagingpfad für SFTP:</strong> <code><?php echo $this->escape($this->data['paths']['staging']); ?></code><br>Große Bestände können dort direkt bereitgestellt werden. Danach diese Seite neu laden. Bestehende Produktbilder werden nicht ersetzt.</div>
<div class="card mb-3"><div class="card-body"><h2>Master bereitstellen</h2><form action="<?php echo Route::_('index.php?option=com_fdshop&task=masterimageimport.upload'); ?>" method="post" enctype="multipart/form-data"><label class="form-label" for="masters">Mehrere PNG-Master oder ZIP-Datei</label><input class="form-control mb-2" id="masters" name="masters[]" type="file" accept=".png,.zip,image/png,application/zip" multiple required><button class="btn btn-primary" type="submit">In Staging übernehmen</button><?php echo HTMLHelper::_('form.token'); ?></form><p class="small text-muted mt-2">PHP-Limits: upload <?php echo $this->escape((string)$this->data['limits']['upload_max_filesize']); ?>, POST <?php echo $this->escape((string)$this->data['limits']['post_max_size']); ?>, Dateien <?php echo $this->escape((string)$this->data['limits']['max_file_uploads']); ?>. Für große Bestände SFTP verwenden. ZIP: <?php echo $this->data['zip']?'verfügbar':'nicht verfügbar'; ?>.</p></div></div>
<div class="d-flex gap-2 align-items-center mb-2"><a class="btn btn-secondary" href="<?php echo Route::_('index.php?option=com_fdshop&view=masterimageimport'); ?>">Dry-Run / Bestand neu einlesen</a><button type="button" class="btn btn-success" id="fdshop-import-start" disabled>Ausgewählte Bilder importieren</button><span id="fdshop-selection">Ausgewählt: 0</span></div>
<div id="fdshop-progress" class="alert alert-secondary d-none" aria-live="polite"></div>
<p><strong>Dateien:</strong> <?php echo count($a['items']); ?> · <strong>READY:</strong> <?php echo (int)($a['counts']['READY']??0); ?> · <strong>ALREADY_IMPORTED:</strong> <?php echo (int)($a['counts']['ALREADY_IMPORTED']??0); ?> · <strong>Review/Fehler:</strong> <?php echo count($a['items'])-(int)($a['counts']['READY']??0)-(int)($a['counts']['ALREADY_IMPORTED']??0); ?></p>
<div class="table-responsive"><table class="table table-striped" id="fdshop-master-table"><thead><tr><th><input type="checkbox" id="fdshop-ready-all" aria-label="Alle READY auswählen"></th><th>SKU</th><th>Masterdatei</th><th>Produkt</th><th>Dimension</th><th>Größe</th><th>Status</th><th>Hinweis</th></tr></thead><tbody>
<?php foreach($a['items'] as $row):?><tr data-sku="<?php echo $this->escape($row['sku']); ?>"><td><?php if($row['status']==='READY'):?><input class="fdshop-ready" type="checkbox" value="<?php echo $this->escape($row['sku']); ?>" aria-label="<?php echo $this->escape($row['sku']); ?> auswählen"><?php endif;?></td><td><?php echo $this->escape($row['sku']); ?></td><td><?php echo $this->escape($row['filename']); ?></td><td><?php echo $this->escape($row['product_name']); ?></td><td><?php echo (int)$row['width']; ?> × <?php echo (int)$row['height']; ?></td><td><?php echo number_format((int)$row['size']/1024,1,',','.'); ?> KB</td><td><span class="badge <?php echo $row['status']==='READY'?'bg-success':($row['status']==='ALREADY_IMPORTED'?'bg-info text-dark':'bg-warning text-dark'); ?> fdshop-status"><?php echo $this->escape($row['status']); ?></span></td><td class="fdshop-message"><?php echo $this->escape($row['message']); ?></td></tr><?php endforeach;?></tbody></table></div>
<form action="<?php echo Route::_('index.php?option=com_fdshop&task=masterimageimport.cleanup'); ?>" method="post" onsubmit="return confirm('Nur den FDShop-Master-Stagingbereich leeren? Importierte Produktbilder und Import-State bleiben erhalten.');"><button class="btn btn-danger" type="submit">Staging vollständig leeren</button><?php echo HTMLHelper::_('form.token'); ?></form>
</div>
<?php $this->getDocument()->getWebAssetManager()->useScript('com_fdshop.admin-master-import'); ?>
